### ISSUE TITLE
Return boarding pass overlaps on the outward voyage.

### ISSUE THREAD

**Issue by sbbastos** [tomasmcguinness/dotnet-passbook#100]
I have a issue with the round trip boarding pass.

When you insert the boarding pass into your wallet and then insert the return card, the return card overlaps the outbound card.

Are there flag that determine whether the boarding pass is a one-way card or a return card?

Thanks in advance

**Comment by tomasmcguinness** [comment]
The groupingIdentifier key might be what you are looking for.

> Optional for event tickets and boarding passes; otherwise not allowed. Identifier used to group related passes. If a grouping identifier is specified, passes with the same style, pass type identifier, and grouping identifier are displayed as a group. Otherwise, passes are grouped automatically.

>Use this to group passes that are tightly related, such as the boarding passes for different connections of the same trip.

>Available in iOS 7.0.

**Comment by sbbastos** [comment]
Hi @tomasmcguinness!

Thanks for your help, but after that I get a doubt:

How I get the grouping Identifier key? On Register an app group?

Thanks again!!!

**Comment by sbbastos** [comment]
Hi, I got the answers!

A friend sent me some expired tickets and I could answer.

The airline concatenates the locator and name and places it as a group identifier.

**Comment by tomasmcguinness** [comment]
Great. Sorry I didn't get back. I was under the weather.

I'll close this ticket as resolved.
