### ISSUE TITLE
Always get same Team ID

### ISSUE THREAD

**Issue by Alik2015** [tomasmcguinness/dotnet-passbook#101]
I created a fresh project in VS and added the passbook generator from NuGet.

My code is as below:

```
            var request = new PassGeneratorRequest();
            request.OrganizationName = "test";
            request.TeamIdentifier = "aaaa";

```
Once my pkpass file is generated I rename it as zip open pass.json and my TeamId is always the same in my case X452LME3NH.

Every other detail matches what i have in code like OrganizationName,Description etc.
I am not sure where the static value is coming from as its a fresh project referencing nuget package.

Further debugging shows that the change happens at following line in PassGenerator.cs

`            if (nameParts.TryGetValue("OU", out teamIdentifier))
`

The Apple certificate was downloaded from the link in readme file for project.

From the development of the iOS app the error is:

Error Domain=PKPassKitErrorDomain Code=1 "The pass cannot be read because it isn’t valid." UserInfo={NSLocalizedDescription=The pass cannot be read because it isn’t valid., NSUnderlyingError=0x600000e5f600 {Error Domain=PKPassKitErrorDomain Code=1 "The passTypeIdentifier or teamIdentifier provided may not match your certificate, or the certificate trust chain could not be verified." UserInfo={NSLocalizedDescription=The passTypeIdentifier or teamIdentifier provided may not match your certificate, or the certificate trust chain could not be verified.}}}

Any help would be appreciated.

**Comment by tomasmcguinness** [comment]
That's interesting.

Let me try and reproduce this.

**Comment by tomasmcguinness** [comment]
I haven't been able to reproduce this issue, nor have any other users of the library report a problem. I'm going to close this ticket.

**Comment by Clarencelollol** [comment]
Hello, I have encountered this issue recently. Please help on this, and this is my pass 
[E5982H-I2.zip](https://github.com/tomasmcguinness/dotnet-passbook/files/5275604/E5982H-I2.zip). I am using IPhone 7 plus to open it.

Many thanks.
