### ISSUE TITLE
Question about configuring dotnet-passbook as an API running in Azure

### ISSUE THREAD

**Issue by faceoffers28** [tomasmcguinness/dotnet-passbook#103]
Cool tool! Quick question for ya. Where do we install or place the Apple certificates, if running in Azure? This is an Asp.Net MVC 5 Web API. I see that you have created a sample web service, but I can't tell from the documentation what to do with the certs, if running in Azure.

https://github.com/tomasmcguinness/dotnet-passbook/tree/new-sample-webservice  

Can you provide any direction or guidance on that? Thanks in advance!

**Comment by tomasmcguinness** [comment]
I just deploy both the certificates in a Certs folder and then load them from the disk as required. Does that help?

**Comment by faceoffers28** [comment]
@tomasmcguinness OK, I think I solved this. I was able to get this working in my Controller and then I pass the path to my Service as a string. This works running on my local machine and the path is actually on my local machine. I assume this will work in Azure, but I have not tested. 

string appleCertPath = Server.MapPath("~/Certs/AppleWWDRCAExp-02-07-2023.cer");

If this is correct, I will close the issue. Thanks!

**Comment by tomasmcguinness** [comment]
That should do it! Remember, that only some of the App Service sizes will work with certificates. I don't think the Free one does. If you get exceptions trying scaling the app service and see if that clears it.

**Comment by tomasmcguinness** [comment]
I'm going to close this issue now, as I haven't heard anything else. @faceoffers28 feel free to repoen if you need further help!

**Comment by faceoffers28** [comment]
@tomasmcguinness From an API perspective, I ended up solving the issue using this method. This works across the board.

`string AppleCertPath = System.Web.Hosting.HostingEnvironment.MapPath(ConfigurationManager.AppSettings["applePassCertPath"]);`

Here is the key added to the Web.config for the API.

`<add key="applePassCertPath" value="~/Certs/AppleWWDRCAExp-02-07-2023.cer" />
`
Hope this helps! Please close this when you get a chance.

**Comment by tomasmcguinness** [comment]
Great to hear you have it working! Thank you for the donation too!
