### ISSUE TITLE
Can't get coupon pass to pop up on iOS device

### ISSUE THREAD

**Issue by faceoffers28** [tomasmcguinness/dotnet-passbook#104]
I'm not sure what I'm doing wrong here, but I've created about 20 or so passes and none of them pop up on my test device. The .pkpass file is getting created, but when I click on it, it pulls up the Apple share and save screen instead of displaying the pass. I can even save the .pkpass as a zip file and I can see all the files.

Here is my code.

var generatorRequest = new PassGeneratorRequest();
generatorRequest.AppleWWDRCACertificate = GetCertificateContents(applePath);
generatorRequest.Certificate = GetCertificateContents(walletPath);
generatorRequest.CertificatePassword = "SOMEPASS";
generatorRequest.AuthenticationToken = secret;
generatorRequest.WebServiceUrl = "https://example.com/passes/";

generatorRequest.PassTypeIdentifier = "TEAMID.pass.com.domainname";
generatorRequest.TeamIdentifier = "TEAMID";
generatorRequest.Description = "TestPass";
generatorRequest.OrganizationName = "COMPANYNAME";
generatorRequest.LogoText = "Pass";
generatorRequest.RelevantDate = Convert.ToDateTime(DateTime.Now.ToString("o"));

generatorRequest.Style = PassStyle.Coupon;
generatorRequest.AddPrimaryField(new StandardField("offer", "Test Offer", "On December 31st"));
generatorRequest.Images.Add(PassbookImage.Icon, File.ReadAllBytes(icon));
generatorRequest.Images.Add(PassbookImage.Icon2X, File.ReadAllBytes(icon2x));
generatorRequest.Images.Add(PassbookImage.Icon3X, File.ReadAllBytes(icon3x));

generatorRequest.AddBarcode(BarcodeType.PKBarcodeFormatQR, serialNumber, "UTF-8", serialNumber);
generatorRequest.SerialNumber = serialNumber;
var generator = new PassGenerator();
var rawPass = generator.Generate(generatorRequest);
return rawPass;

I used the images from the Coupon.pass example found here.

Download this book’s companion file (from the developer downloads area), and locate the coupon in the Sample Passes directory.

[](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/YourFirst.html)

At this point, I'm just trying to find the minimal code to create a basic coupon. :)

Any help is much appreciated! Thanks!

**Comment by tomasmcguinness** [comment]
Could you send me one of the pkpass files?

**Comment by faceoffers28** [comment]
I sent an email with "Can't get coupon pass to pop up on iOS device #104" in the subject line. Cheers!

**Comment by faceoffers28** [comment]
Wow, I finally got it to work. The AuthenticationToken has to be at least 16 characters long. I was using 12345 just to test with. I can't believe I wasted so many hours on something so simple. :)

**Comment by tomasmcguinness** [comment]
Great to hear.

I'm going to add that check to my Pass Validator.

Tom
________________________________
