### ISSUE TITLE
Automatic-Update for android devices

### ISSUE THREAD

**Issue by furkanesen6** [tomasmcguinness/dotnet-passbook#105]
Hey there! 👋

I have some trouble about auto-update on android devices. So, I managed to create some passes with your code. Also, I can update my passes manually. But, I can not automatically update my passes on android devices. Even if passbook getting updated very well manually and automatically on apple wallet.  

I am using Wallet Passes for android. I did every steps under the title "sending push notifications to the app" of Wallet Passess's documentation ( https://walletpasses.io/developer/ ) And, I am getting 200 https response but it is not update or send notifications to my wallet. probably, I am mising something. or I misunderstand what it is doing. :)

so, do you have any advice about auto-update for android devices. 

Thanks in advance!

**Comment by tomasmcguinness** [comment]
Does the pass installed via Android contact your WebService?

**Comment by furkanesen6** [comment]
it is connecting when registration but does not send a request for latest version of pass when I send a post request to ( https://walletpasses.appspot.com/api/v1/push ) from postman with this body:
{
    "passTypeIdentifier": "my pass type Identifier",
    "pushTokens": "my pass push token"   
}
and this headers:

Content-Type: application/json
Authorization: 39b38fb5566541adb03bda580eb00a73

**Comment by furkanesen6** [comment]
it is connecting when registration but does not send a request for latest version of pass when I send a post request to ( https://walletpasses.appspot.com/api/v1/push ) from postman with this body:
{
"passTypeIdentifier": "my pass type Identifier",
"pushTokens": "my pass push token"
}
and this headers:

Content-Type: application/json
Authorization: 98956asfa84e15g8v4s6f9sf

**Comment by furkanesen6** [comment]
it is connecting when registration but does not send a request for latest version of pass when I send a post request to ( https://walletpasses.appspot.com/api/v1/push ) from postman with this body:
{
"passTypeIdentifier": "my pass type Identifier",
"pushTokens": "my pass push token"
}
and this headers:

Content-Type: application/json
Authorization: (my authorization no)

**Comment by tomasmcguinness** [comment]
Hi @furkanesen6 I'm going to close this ticket as I haven't hear anything further from you. 

If you find the dotnet-passbook library to be useful, please consider making a donation https://www.buymeacoffee.com/fMKJ2NnQ3

**Comment by Bashayr29** [comment]
Hi, I'm facing the same issue!
Any solution?
