### ISSUE TITLE
Change the font color of label value

### ISSUE THREAD

**Issue by dheerajkumar1** [tomasmcguinness/dotnet-passbook#107]
Can you please tell me about that how can i change the font color of label value?
I am able to find to change the color of label but not able to change the color of its value

thanks

**Comment by tomasmcguinness** [comment]
Unfortunately, I believe the label value is set by the ForegroundColor of the pass and can't be changed.

**Comment by dheerajkumar1** [comment]
![Capture](https://user-images.githubusercontent.com/44186754/70685800-729eb380-1cd0-11ea-84f0-e6bb8ccaad76.PNG)


i need to create pass design like attached screenshot is it possible to create design with your package

**Comment by tomasmcguinness** [comment]
Sadly, it's no possible to be that specific about the layout and positioning of the fields. 

You could use a label color of white and a foreground color of black there. 

If you used a Stripe image with the same background colour and the word adult down the side, you could probably get a little closer to this design, but you're probably not going to be able to match this completely.

This is down to the way Apple render the passes.

Please review Apple's documentation. https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/Creating.html

From that, perhaps an Event style ticket with a background image would be the closest. The primary field could be the event name with the Name and When as secondary fields. I recommend experimenting with the different styles.

**Comment by tomasmcguinness** [comment]
As I haven't head anything on this ticket, I'm going to close it.
