### ISSUE TITLE
Row Support for Event Pass Types

### ISSUE THREAD

**Issue by jedmondson1** [tomasmcguinness/dotnet-passbook#109]
Hello,
We are currently trying to achieve a three row event ticket layout as pictured here. 
![Screen Shot 2019-12-18 at 3 52 09 PM](https://user-images.githubusercontent.com/51919842/71122382-750c7c00-21ae-11ea-955e-c28eedff3d3d.png)
![Screen Shot 2019-12-18 at 3 54 50 PM](https://user-images.githubusercontent.com/51919842/71122504-c1f05280-21ae-11ea-9e56-ded1fb48406c.png)
According to this [WWDC](https://developer.apple.com/videos/play/wwdc2018/720/) (@ 19 min) video you are able to add a "row" key value pair onto auxiliary fields to achieve this. Are there any  plans to add this feature? Or are there any current workouts that could help us achieve this?

Thanks!

**Comment by tomasmcguinness** [comment]
Hi @jedmondson1 

Thanks for letting me know about this missing property. I've added the Row property to the Field class, so this should be available to you now.

2.0.2 of the Nuget package has been published to, which includes this change.

Please let me know if that works for you as expected!

If you do find this library useful, please consider donating https://www.buymeacoffee.com/fMKJ2NnQ3

**Comment by jedmondson1** [comment]
Hi @tomasmcguinness ,

Thank you for such a timely response! Everything is working as expected.
