### ISSUE TITLE
Add support for Apple Wallet Semantic Tags

### ISSUE THREAD

**Issue by linuxct** [tomasmcguinness/dotnet-passbook#113]
Hey there!  

Apple has provided a documentation on how Passbooks can be restructured for Apple Wallet using a new functionality called Semantic Tags. It can be checked [here](https://developer.apple.com/documentation/passkit/wallet/supporting_semantic_tags_in_wallet_passes).  

Currently, the way dotnet-passbook works is with "headerFields", "primaryFields", "secondaryFields", "auxiliaryFields" and "backfields" - but the new "semantics" section can provide extra info.  

After this, do you have any plans on adding this functionality to your solution?  
Thank you!

**Comment by tomasmcguinness** [comment]
Hello. 

I didn't know this was present in the spec. I'll try and it get it added before the end of the month!

Regards,
T

**Comment by linuxct** [comment]
Hey @tomasmcguinness, any news regarding this?

**Comment by tomasmcguinness** [comment]
None, sorry. I haven't had any time to devote to it. I'll update this issue when I have more information.

**Comment by AshleyMedway** [comment]
@tomasmcguinness I can take a look at this if you are #lookingforhelp :)

**Comment by tomasmcguinness** [comment]
This is a very, very long time coming, but I've started work on including support for semantic tags. I hope to get this work done relatively quickly.

**Comment by cyrildurand** [comment]
Thanks for the update, I saw you also published the package to nuget today. 

Great job !

**Comment by tomasmcguinness** [comment]
Please try it out! If you have any issues, let me know!
