### ISSUE TITLE
Problem with generated file

### ISSUE THREAD

**Issue by nicky906** [tomasmcguinness/dotnet-passbook#114]
I have been following your guide and there is a problem with the file I generate at the end. On windows it is not saving as a .pkpass file (this is my first time with this kind of file) however when I upload the file as is to your helper it says it has met all the criteria. When I run through Conveyor the code runs without any errors but I am just shown an error on the iPhone saying 'safari can't download this file', do you have any suggestions about something I may have missed?

**Comment by tomasmcguinness** [comment]
Hi.

What was the issue? 

I'd like to try and make the documentation clearer if I can.

**Comment by nicky906** [comment]
Hey,

I found it in another closed thread that my 'serial number' wasn't large enough, I was just putting a simple word in there to test. I think in another thread someone said it had to be 16 characters or more to be recognised through safari and launch as a ticket, otherwise it didn't recognise the file as being something to create a ticket with and I would get the safari error.

Hope that helps, your plugin has been a lifesaver!

**Comment by tomasmcguinness** [comment]
Interesting. I'll be sure to add that check to my validator! Thx.

If you find the library useful, please consider making a donation - https://www.buymeacoffee.com/fMKJ2NnQ3

**Comment by nicky906** [comment]
Will do!
