### ISSUE TITLE
How to get pass JSON data?

### ISSUE THREAD

**Issue by nitinpatil** [tomasmcguinness/dotnet-passbook#116]
Hello,

I am able to generate pass with the help of "PassGenerator", but I need JSON value of the pass i.e. "pass.json" file content.
Is there any method available which returns JSON of the generated pass?

Thanks,
Nitin

**Comment by tomasmcguinness** [comment]
That is not possible without making changes to the code itself.

Please take a look at the CreatePassFile method on PassGenerator.

You can do something similar to this method in your own code. Create the PassGeneratorRequest as you normally do and then call the Write method. 

Does this help?

**Comment by nitinpatil** [comment]
Hi,

Actually I have implemented Update pass process and Get Pass API expecting JSON of wallet pass to update the PASS in users wallet.
Do we need to add addtional code to convert PassGeneratorRequest  to pass.JSON file JSON string?

**Comment by tomasmcguinness** [comment]
When implementing the method,

webServiceURL/version/passes/passTypeIdentifier/serialNumber

you need to return the entire pkpass file.

**Comment by tomasmcguinness** [comment]
Did you have any success with your update webservice?

**Comment by Faisal0sal** [comment]
I'm also facing the same difficulties. I'm not able to install the pkpass alone. How do you guys do it without pass.json?
