### ISSUE TITLE
Share Pass not displayed on back of pass iOS 13.3 and 13.3.1

### ISSUE THREAD

**Issue by faceoffers28** [tomasmcguinness/dotnet-passbook#117]
I've got an iPhone 6s running 12.1.4 and SharingProhibited = false is set when generating the pass. The back of the pass shows Share Pass on my device and I'm able to click on the button to bring up the Share options. We've tested with some other devices. One is running iOS 13.3 and the other is running 13.3.1 and the Share Pass option does not display.

My code.

`generatorRequest.SharingProhibited = false;`

Is anyone else having this issue? 

Has the field been changed in iOS 13+?

Is there an Apple SDK that works with donet-passbook that I need to update from time-to-time?

Any help is much appreciated. Thanks!

**Comment by tomasmcguinness** [comment]
Hi,

SharingProhibited should be set to true in order to disable the sharing of passes.

Tom

**Comment by faceoffers28** [comment]
Thanks for the quick response. If I set it to true, then sharing is disabled and the Share Pass option does not appear on any of our test devices. This works as expected.

I assume it is an issue with iOS 13, but I have not been able to test on any other iOS 13 devices other than 13.3 and 13.3.1.

Is there some sort of setting that needs to be enabled on iOS 13 to allow this feature to work normally?

**Comment by faceoffers28** [comment]
I was able to test, personally, on a 13.3.1 device today. We were able to share the pass. It looks like the Share Pass language has been removed in iOS 13x. Now, you have to click on the up arrow, located on the upper right-hand side of the back of the pass to share it.
