### ISSUE TITLE
Update NuGet Package

### ISSUE THREAD

**Issue by danielbigler** [tomasmcguinness/dotnet-passbook#118]
Hello,

could you please release a new version of the NuGet Package with .NET 4.5 support ([Fixed here](https://github.com/tomasmcguinness/dotnet-passbook/pull/115)).

Thanks,
Daniel

**Comment by tomasmcguinness** [comment]
Sure. I will do that at the weekend.

**Comment by tomasmcguinness** [comment]
Sorry, I didn't get an opportunity to get around to this due. Should have it resolved in the next few days.

**Comment by tomasmcguinness** [comment]
Sorry this took so long!! 2.0.3 is now published.

**Comment by tomasmcguinness** [comment]
If you find this library useful, please consider sponsoring me. You can use the Sponsor button at the top of the page or visit https://ko-fi.com/tomasmcguinness - thanks!
