### ISSUE TITLE
How to Mark pass as Redeemed?

### ISSUE THREAD

**Issue by nitinpatil** [tomasmcguinness/dotnet-passbook#121]
Hi 

I want to mark the pass as redeemed, can you suggest how to mark the pass as redeemed or used ?

Thanks,
Nitin

**Comment by tomasmcguinness** [comment]
Hi, Nitin,

There are two options:

Voided and ExpirationDate 

You can read more about them here - https://developer.apple.com/library/archive/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/TopLevel.html under the Expiration Keys heading

I hope this helps!

**Comment by nitinpatil** [comment]
yes got it 
Thanks for your help

**Comment by tomasmcguinness** [comment]
If you find the library useful, please consider donating - https://www.buymeacoffee.com/fMKJ2NnQ3
