### ISSUE TITLE
Value for key 'userInfo' must be of class NSDictionary

### ISSUE THREAD

**Issue by stroborobo** [tomasmcguinness/dotnet-passbook#123]
Hello!

When validating passes using the iPhone Simulator, it reports errors for any userInfo data that is not a dictionary. While [the archived documentation][ad] says it's "any JSON data", [the PassKit API docs][pa] says it's `[AnyHashable : Any]?`.

I guess the [`PassGeneratorRequest.UserInfo`][src] should not be of type `Object`, but rather `IDictionary<object, object>`. Am I reading this wrong or would you agree?

Thank you and have a nice day!

[ad]: https://developer.apple.com/library/archive/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/TopLevel.html#//apple_ref/doc/uid/TP40012026-CH2-SW8
[pa]: https://developer.apple.com/documentation/passkit/pkpass/1618794-userinfo
[src]: https://github.com/tomasmcguinness/dotnet-passbook/blob/1468154/Passbook.Generator/PassGeneratorRequest.cs#L240

**Comment by tomasmcguinness** [comment]
You are correct! I can't remember why I made this an object! 

Other examples where UserInfo is represented as dictionary:

https://dev.passkit.net/#create-a-pass
https://docs.microsoft.com/en-us/dotnet/api/passkit.pkpass.userinfo?view=xamarin-ios-sdk-12

I'll try and get a fix in as soon as I can.

Thanks!

**Comment by tomasmcguinness** [comment]
I've just pushed a small update which makes UserInfo a string,object dictionary. I think using string as the key type will prevent serialization issues in the JSON.

**Comment by stroborobo** [comment]
Great, thank you!

**Comment by tomasmcguinness** [comment]
If you find the library useful, please consider supporting it by buying a coffee - https://ko-fi.com/tomasmcguinness
