### ISSUE TITLE
Adding new lines in backfields

### ISSUE THREAD

**Issue by Faisal0sal** [tomasmcguinness/dotnet-passbook#124]
As the title suggests. I have been trying to add new lines in the backfields, so far I have tried 
\r\n 
\n
<br/>

all are not working

**Comment by tomasmcguinness** [comment]
It's \n for newlines. I'm not 100% sure why it's not working for you.

Apple's documentation indicates it will work - https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/Creating.html

Could you share your pkpass file?

**Comment by Faisal0sal** [comment]
You can try getting my passbook when registering here: 

https://loyapro.com/c-r/17

just the fill the field with random text and a for phone number set it 0555555555

you'll see i'm using \n with no success

**Comment by tomasmcguinness** [comment]
Hi,

Did you ever have any success with this?

**Comment by tomasmcguinness** [comment]
It does mention in the documents 

`
 escaped in the JSON file as \n.
`

Perhaps this is the key?
