### ISSUE TITLE
Pass is override the existing pass.

### ISSUE THREAD

**Issue by dheerajkumar1** [tomasmcguinness/dotnet-passbook#125]
I have generated two passes from this library. but when i add one pass it's added successfully to the wallet but when i try to add second pass it override the previous one.

It should be treated as a new pass.

can you please help me in this?

**Comment by tomasmcguinness** [comment]
Hi,

This will happen if the pass type identifier and serial numbers are the same. 

Check that you aren't generating a pass with the same values.

Tom

**Comment by dheerajkumar1** [comment]
Thanks It's working now.

Can you please also let me know the use of AssociatedStoreIdentifiers and TeamIdentifier?

**Comment by tomasmcguinness** [comment]
The TeamIdentifier is related to your Apple developer account and the pass type identifier you are using. These values come from Apple and don't change.

The AssociatedStoreIdentifiers allow iOS to determine which apps are related to your pass. They can give you a way to tap an icon on the pass, which will open the app directly. The identifiers are just the bundle Ids.

I hope this helps.
