### ISSUE TITLE
Group name after adding wallet

### ISSUE THREAD

**Issue by dheerajkumar1** [tomasmcguinness/dotnet-passbook#126]
Hello,
how you get the events to group together look below? There’s a gap between orders?

can you please help me regarding this?

screenshot is attached with this note.
![sd](https://user-images.githubusercontent.com/44186754/91525564-6a021200-e91f-11ea-845e-994ee79bc2f8.jpg)

**Comment by tomasmcguinness** [comment]
Hi,

Apologies for the very long delay.

Do you still need any help with this issue?

Tom
