### ISSUE TITLE
Passbook cannot be installed to passbook

### ISSUE THREAD

**Issue by Clarencelollol** [tomasmcguinness/dotnet-passbook#128]
I follow the tutorial and validate the pass on https://pkpassvalidator.com/. But after I open the pass on mobile phone, the pass cannot be installed and the debug log show "Invalid Data error reading pass. The passTypeIdentifier or teamIdentifier provided may not match your certificate, or the certificate trust chain could not be verified." 
Please help on this, many thanks. 

This is my passbook
[E5982H-I2 (2).zip](https://github.com/tomasmcguinness/dotnet-passbook/files/5297084/E5982H-I2.2.zip)

**Comment by tomasmcguinness** [comment]
Sorry for the long delay in replying.

Do you still need help with this issue?

**Comment by Clarencelollol** [comment]
Thanks. The issue is resolved, I used the wrong certificate.
