### ISSUE TITLE
Unable to load certificate from file

### ISSUE THREAD

**Issue by hfeiges** [tomasmcguinness/dotnet-passbook#129]
Hello,

So in my project, I have been unable to load the certificate (the local .pfx one, with the private key) from a file, without some modification of the PassGenerator.cs source file (more on this below)..

It seems that when you use the MachineKeySet flag, even if you (the user under which the application is running) have administrative permissions to the machine, you still get access denied errors for attempting to use the certificate with a password.  

Reading up on this issue, it seems that under some windows versions this might not be an issue, while on others you might have to play around with permissions to certain system directories (such as C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys, etc..).   However no matter what I tried, with the certificate file or attempting to change permissions within the system folders (I am developing on a windows 10 machine), I was just unable to get it to work.

I was able to bring up the certificate and sign passbook files when I registered it with the certificate manager and used the thumbprint to look up the certificate, etc, so that worked, but I was unable to get my application to run by loading the certificate from a file..

Anyhow, after some research and diving into the code a little bit, I finally **was** able to get the certificate from file to work with some modification to the source code:

in file: PassGenerator.cs
in function: GetCertificateFromBytes

Change the code:
from: `X509KeyStorageFlags flags = X509KeyStorageFlags.MachineKeySet | X509KeyStorageFlags.Exportable;`
to:  `X509KeyStorageFlags flags = X509KeyStorageFlags.UserKeySet;`

Once I did that and re-compiled the library, the .PFX file was able to load and I was able to sign passbook passes..

I am not entirely sure if this is a good solution though, since I really do not know what the full impact of that change is going to be (I do not have a whole lot of expertise on cryptographic certificates, and how they interact with the windows OS)...   This could be great just for solving my problem here for my project, but will it break other projects?

Perhaps someone with more knowledge than myself could look at this and submit the code change (or something similar) to the project and fix it so we could use file-based crypto certificates rather than system-imported ones??

Thanks..

... Howard

**Comment by tomasmcguinness** [comment]
Hi Howard, 

Sorry it's taken me so long to reply to this. In these instances, it's best to provide the underlying byte[] of the certificates. 

These flags have caused me countless issues since I first released this project. 

I'll take a look at the UserKeySet change in more detail.

Thanks!

**Comment by tomasmcguinness** [comment]
In the next version, which I've started working on, I'll be changing how certificates are loaded. The plan is to have the PassGeneratorRequest accept X509 certificates directly, so the loading/keys etc. can be handled by the caller.
