### ISSUE TITLE
Pass.pkpass not accepted by apple wallet

### ISSUE THREAD

**Issue by devhelpr** [tomasmcguinness/dotnet-passbook#130]
Hi,

Whatever I do, I can't get my generated pass to be accepted by the Apple wallet.
The file is downloading, and I have put it through https://pkpassvalidator.azurewebsites.net/.
The only error that I get there is WWDR Certificate Subject.
I've added the most recent AppleWWDRCAG3.cer file to my project.
The certificate of the pass itself is generated through the Apple portal and I've added the p12 file which contains both private and public keys.
I've verified the team id and pass id, both matches the data which is entered on the Apple portal.
When I connect my iphone to xcode, I get the messages:

- Invalid data error reading pass pass.nl.digitaleledenpastest/12345678-c619b82e-2521-44ac-868a-4344c6906634. The passTypeIdentifier or teamIdentifier provided may not match your certificate, or the certificate trust chain could not be verified.
- PassBook Pass download failed: Error Domain=PKPassKitErrorDomain Code=1 "(null)"

This is the code that I use to generate the pkpass file and return it from the webapi controller:

```
PassGenerator generator = new PassGenerator();
                PassGeneratorRequest request = new PassGeneratorRequest
                {
                    PassTypeIdentifier = "[Pass identifier I created in the apple portal]",
                    TeamIdentifier = "[TEAMIDENTIFIER]",
                    SerialNumber = claimsIdentity.GetEsbUserLidnummer() + "-" + Guid.NewGuid(),
                    Description = "Digitale Ledenpas Test",
                    OrganizationName = "M van de Lisdonk",
                    LogoText = "Digitale Ledenpas Test",

                    BackgroundColor = "#0099DC",
                    LabelColor = "#FFFFFF",
                    ForegroundColor = "#FFFFFF"
                };

                byte[] certData = File.ReadAllBytes(HttpContext.Current.Server.MapPath(@"~/Resources/AppleCertificates/pass-digitaleledenpass.p12"));
                request.Certificate = certData;
                request.CertificatePassword = "Test123!";
                request.AppleWWDRCACertificate = File.ReadAllBytes(HttpContext.Current.Server.MapPath(@"~/Resources/AppleCertificates/AppleWWDRCAG3.cer"));
                
                byte[] icon1 = File.ReadAllBytes(HttpContext.Current.Server.MapPath(@"~/assets/img/layout/passkit/apple-touch-icon.png"));
                byte[] icon2 = File.ReadAllBytes(HttpContext.Current.Server.MapPath(@"~/assets/img/layout/passkit/apple-touch-icon@2x.png"));
                byte[] icon3 = File.ReadAllBytes(HttpContext.Current.Server.MapPath(@"~/assets/img/layout/passkit/apple-touch-icon@3x.png"));

                request.Images.Add(PassbookImage.Icon, icon1);
                request.Images.Add(PassbookImage.Icon2X, icon2);
                request.Images.Add(PassbookImage.Icon3X, icon3);

                request.Style = PassStyle.Generic;

                request.AddBarcode(BarcodeType.PKBarcodeFormatQR, claimsIdentity.GetEsbUserLidnummer(), "ISO-8859-1", claimsIdentity.GetEsbUserLidnummer());

                byte[] generatedPass = generator.Generate(request);

                HttpResponseMessage responsePass = Request.CreateResponse(System.Net.HttpStatusCode.OK);
                var dataStream = new MemoryStream(generatedPass);
                responsePass.Content = new StreamContent(dataStream);
                responsePass.Content.Headers.ContentType = new MediaTypeHeaderValue("application/vnd.apple.pkpass");
                responsePass.Content.Headers.ContentDisposition = new ContentDispositionHeaderValue("attachment")
                {
                    FileName = "pass.pkpass"
                };
                responsePass.Content.Headers.LastModified = DateTime.Now;                
                return responsePass;
```

I hope anyone here can help, since I've run out of options. Thanks in advance!

Kind regards,
Maikel van de Lisdonk

**Comment by devhelpr** [comment]
Hi,

Could it be that APPLE_CERTIFICATE_THUMBPRINT = "FF6797793A3CD798DC5B2ABEF56F73EDC9F83A64" doesn't match the latest apple wwdr certificate?

I'll try to verify this myself this weekend

Kind regards,
Maikel

**Comment by JArmandoCl** [comment]
Im getting the same error :/ please share your results

**Comment by devhelpr** [comment]
Yes I will share the results. If I find a fix I'll even gladly make a PR

**Comment by JArmandoCl** [comment]
Downloading this certificate i made it work, you could try :)

![image](https://user-images.githubusercontent.com/58884118/101212316-21ed3c80-363e-11eb-8866-9ff28fef0ca5.png)

**Comment by devhelpr** [comment]
I currently use the one with date 2030 myself. So signing with the certificate of 2023 works? For me that would be the solution for now because I want to demo this to my stakeholders tuesday :-)

**Comment by JArmandoCl** [comment]
Yes! Works with the 2023 i have tested it now and could create my pass :) try it

**Comment by devhelpr** [comment]
Thanks! Thats the first I will do tomorrow morning🤓☕️

**Comment by tomasmcguinness** [comment]
Hello,

It seems like you figured out the solution. 

It's possible that all new pkpass certificates that are generated are signed with the newest WWDR certificate. This is backed up with the "certificate trust chain" error. I'll take a look at my pass validator to see why it's generating that subject error.

Regards,
Tom

**Comment by devhelpr** [comment]
Hi,

I just tested it with the apple wwdr certificate with enddate 2023, and now my pass works as well. Cool!

The subject error in the pass validator is caused by the new certificate as well: it's subject has changed a little bit, the order of the fields in the subject has changed so the string compare fails.
Perhaps its a good idea to mention the end date of the wwdr certificate that the nuget package and the validator website uses in the readme of the repositories and on the validator website.

Do you want me to submit a PR or do you make the changes yourself? I am happy to help if needed,

Kind regards,
Maikel

**Comment by penumbra23** [comment]
Hi everyone!

I'm having the same problem opening the pkpass file in Apple Wallet. Here is my almost copy-pasted code from Tom's README.

```cs
PassGenerator generator = new PassGenerator();
PassGeneratorRequest request = new PassGeneratorRequest();
request.PassTypeIdentifier = "pass.com.company.example";
request.TeamIdentifier = "R4455RTX1222";
request.SerialNumber = "121212121212121212121212";
request.Description = "Some event";
request.OrganizationName = "My Company";
request.LogoText = "Company Pass";
request.BackgroundColor = "#FFFFFF";
request.LabelColor = "#000000";
request.ForegroundColor = "#000000";
request.Style = PassStyle.BoardingPass;

request.AssociatedStoreIdentifiers.Add(551768478);
request.AddPrimaryField(new StandardField("origin", "San Francisco", "SFO"));
request.AddPrimaryField(new StandardField("destination", "London", "LDN"));

request.AddSecondaryField(new StandardField("boarding-gate", "Gate", "A55"));

request.AddAuxiliaryField(new StandardField("seat", "Seat", "G5"));
request.AddAuxiliaryField(new StandardField("passenger-name", "Passenger", "Thomas Anderson"));

request.Images.Add(PassbookImage.Icon, System.IO.File.ReadAllBytes("../icon.png"));
request.Images.Add(PassbookImage.Icon2X, System.IO.File.ReadAllBytes("../icon2x.png"));

request.TransitType = TransitType.PKTransitTypeAir;

byte[] certData = System.IO.File.ReadAllBytes(@"../certificate.pfx");
request.Certificate = certData;

byte[] wwdrData = System.IO.File.ReadAllBytes(@"../AppleWWDRCA.cer");
request.AppleWWDRCACertificate = wwdrData;

byte[] generatedPass = generator.Generate(request);
return new FileContentResult(generatedPass, "application/vnd.apple.pkpass");
```

I'm using the older WWDR certificate, not the G3 one and have my key and cert combined in a pfx formatted file. The validation passes, but my iPhone can't register the file as a `.pkpass` file, but as a zip archive.

Could it be something with the EOL chars because I'm generating the pass file on a Windows machine?

**Comment by penumbra23** [comment]
Okay I've figured out what's going wrong... Some fields (for which I couldn't find any documentation on Apple's Developer Portal) are mandatory. Without them the application won't open the `pkpass` file correctly.

**Comment by devhelpr** [comment]
Thats valuable info for future visitors of this thread, can you add the fields which you find were mandatory? Thanks and kind regards, Maikel

**Comment by penumbra23** [comment]
I've tested only for `PassStyle.EventTicket`s but I suppose it's the same thing for any ticket style (again, couldn't find any relevant docs for it):
- passTypeIdentifier
- teamIdentifier
- serialNumber
- description
- logoText
- organizationName
- background, foreground and labelColor
- logo & logo2x
- icon & icon2x
- header field
- one primary field

Without any of these the `pkpass` file wasn't working for me on Apple Wallet App.

**Comment by tomasmcguinness** [comment]
Perhaps the library could throw some errors if mandatory fields are missing?

**Comment by brallierc** [comment]
We implemented this and it was all working for several months, however just recently (maybe in December) it stopped working and now when users try to download their pass they get an error from safari. Does anyone have any thoughts as to why this stopped working for us?

**Comment by tomasmcguinness** [comment]
Hi. Are you using the latest WWDR certificate? Have you tried to regenerate your PKpass certificate?

**Comment by angelru** [comment]
Hello, I did not want to open a new issue, the pass is not seen on iOS, on android it is, the validator gives me everything as ok.
![Captura de pantalla 2022-08-23 095412](https://user-images.githubusercontent.com/11645585/186103621-bb366706-1335-45ee-ad96-1b78261af4b2.png)
