### ISSUE TITLE
Unable to set Field.DataDetectorTypes

### ISSUE THREAD

**Issue by IGx89** [tomasmcguinness/dotnet-passbook#132]
Hello! First off, thanks so much for this library! It's been very helpful, and appreciate the work you've done on this.

Wanted to submit a minor bug report: it doesn't appear possible to set Field.DataDetectorTypes. The property is `internal set` and the StandardField constructor that takes a DataDetectorTypes object doesn't actually do anything with it (guessing that's unintentional).

Thanks!

**Comment by tomasmcguinness** [comment]
Hi. Let me take a look at this and get back to you!

**Comment by MacFriis** [comment]
Hi I'm working with the Danish Health department and we are trying to use your package, but we also have the issue. that we can't disable the data detection. We would much appreciate if you had the time to look at it in the near future.
Then you can say that you help with opening Denmark 
Thanks

**Comment by tomasmcguinness** [comment]
I've pushed some changes, which removes the internal modifier from the DataDetectorTypes property and also corrects the StandardField's use of the dataDetectorTypes parameter. Please me know if this helps!

**Comment by MacFriis** [comment]
Thanks, it is working, when I done, I’ll send you some view of the Danish Corona pass version

On 14 Apr 2021, at 21.50, Tomas McGuinness ***@***.******@***.***>> wrote:



I've pushed some changes, which removes the internal modifier from the DataDetectorTypes property and also corrects the StandardField's use of the dataDetectorTypes parameter. Please me know if this helps!

**Comment by tomasmcguinness** [comment]
Excellent. Let me know if I can help further. I'm going to close this ticket now.

**Comment by IGx89** [comment]
Thanks a lot Tomas! I'll check it out in the next week or two, but sounds like it should work great. Appreciate it!
