### ISSUE TITLE
add loyalty card to apple wallet

### ISSUE THREAD

**Issue by junaidgoharhashmi** [tomasmcguinness/dotnet-passbook#138]
can we add loyalty card to apple wallet through this package?

**Comment by tomasmcguinness** [comment]
What do you mean by loyalty card?

**Comment by junaidgoharhashmi** [comment]
I want to add my loyalty or gift card in to apple wallet.

Sent from Yahoo Mail on Android 
 
  On Wed, Nov 10, 2021 at 4:03 PM, Tomas ***@***.***> wrote:   


What do you mean by loyalty card?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tomasmcguinness** [comment]
Yes, you can create a pass using this library. Apple suggest using the StoreCard type for loyalty cards.

**Comment by tomasmcguinness** [comment]
I'm closing this due to age.

**Comment by hjavaher** [comment]
Hi,
I think he was talking about adding the generated pass to the apple wallet. The example in the repo just generates the pass. What's the easiest way of opening the pass and adding it to the wallet?

Thank you

**Comment by tomasmcguinness** [comment]
Oh, sorry.

Two options I think. First is to install the pass using an app. iOS has an API that will launch the Wallet app and ask the user to add the pass. The second option is to open it via a URL and return the file with a MIME type of application/vnd.apple.pkpass.
