### ISSUE TITLE
The specified network password is not correct.

### ISSUE THREAD

**Issue by faceoffers28** [tomasmcguinness/dotnet-passbook#139]
I'm not sure when this problem started, but I'm trying to install a new/updated PFX file and I'm running into this issue. I've tried with a password that I know is good and I've tried with no password. Does anyone have a workaround for this? I'm running version 2.0.2 on Asp.net 4.7.2. I have since upgraded to 2.0.6 with no luck.

I'm loading my certs as byte[]. This all used to work just fine. This was months ago before trying to install a new/updated PFX file. 

Might be related to this issue.
https://github.com/tomasmcguinness/dotnet-passbook/issues/129

Any help is greatly appreciated! Thanks in advance!

**Comment by faceoffers28** [comment]
I created my new PFX file using openssl version 3.0.0 (7 sep 2021). I'm going to try an older version of openssl that I know worked last time I updated the PFX file.

**Comment by faceoffers28** [comment]
Hmmm.... I created a new PFX using openssl version 1.1.1h (22 Sep 2020) and it worked. I'm now able to sign the passes. I have no idea what the issue could be between X509Certificate2 and openssl. I'm getting the error from the following line of code in the GetCertificateFromBytes method on the PassGenerator.cs file.

`X509Certificate2 certificate = new X509Certificate2(bytes, password, flags);`

**Comment by faceoffers28** [comment]
This is interesting! Looks like we should be using the Certificate Store or disposing of the PFX file after usage.  https://snede.net/the-most-dangerous-constructor-in-net/

**Comment by tomasmcguinness** [comment]
I'll have to look into this. My next release of dotnet-passbook will move the ownership of the PFX out of the library, so the caller will supply a reference, rather than a byte array and password.

**Comment by tomasmcguinness** [comment]
Hi. I've merged in my changes #146 so certificates are no longer opened by this library. It's not the caller's responsibility to provide the proper X509 certificate. This will hopefully resolve these issues.
