### ISSUE TITLE
How to get Apple WWDRC certificate using Azure?

### ISSUE THREAD

**Issue by faceoffers28** [tomasmcguinness/dotnet-passbook#140]
I was able to upload the Apple WWDRC public cert to Azure and I have a thumbprint, but I don't see any easy way to call it. I see that you have some code here, but it doesn't work. Is this a work in progress? I see that you have mentioned in your instructions that the only way to call is byte[].  I assume that if we are calling byte[] that we are filling up diskspace as discussed here. https://snede.net/the-most-dangerous-constructor-in-net/

`return GetSpecifiedCertificateFromCertStore(APPLE_CERTIFICATE_THUMBPRINT, StoreName.CertificateAuthority, X509FindType.FindByThumbprint);`

PassGenerator.cs
```
private X509Certificate2 GetAppleCertificate(PassGeneratorRequest request)
        {
            Trace.TraceInformation("Fetching Apple Certificate...");

            try
            {
                if (request.AppleWWDRCACertificate == null)
                {
                    return GetSpecifiedCertificateFromCertStore(APPLE_CERTIFICATE_THUMBPRINT, StoreName.CertificateAuthority, X509FindType.FindByThumbprint);
                }
                else
                {
                    return GetCertificateFromBytes(request.AppleWWDRCACertificate, null);
                }
            }
            catch (Exception exp)
            {
                Trace.TraceError("Failed to fetch Apple Certificate: [{0}]", exp.Message);
                throw;
            }
        }
```

Thanks!

**Comment by tomasmcguinness** [comment]
Version 3 of the library, created by #146 now requires that you provide the WWDR certificate as an X509 instance. You're free to load this certificate any way you wish. This will allow you to manage the cert yourself.
