### ISSUE TITLE
Support for EAN13 Barcode type

### ISSUE THREAD

**Issue by kknd4eva** [tomasmcguinness/dotnet-passbook#145]
Hi there, 

I was wondering if there's an easy way for me to add support for the EAN13 barcode type to this package? I'm happy to do the work myself if needed, and it seems Apple Wallet supports it, but I couldn't see it in the types this library has available, and I'm not 100% sure how to go about adding support myself.

**Comment by tomasmcguinness** [comment]
Hi,

As far as I know, Wallet doesn't support EAN13 type barcodes. The nearest support is EAN128. 

Of course, you could generate an image of the EAN13 barcode and place it into the Strip image part of the pass, but these has it's own limitations.

Sorry.
