### ISSUE TITLE
"The buffer supplied to a function was too small" cryptographic exception with certificate signing

### ISSUE THREAD

**Issue by olegmedv** [tomasmcguinness/dotnet-passbook#148]
Hello! 1 of 5 times I get this error. What is wrong with signing? I send same parametres to method each time. Why is it failed? And can I increase buffer? Thanks for any advice.
`     private void SignManifestFile(PassGeneratorRequest request)
        {
        .........
        signing.ComputeSignature(signer);
        `
![image](https://user-images.githubusercontent.com/63075175/155094334-e7855b63-5801-41ed-94ef-1f429ab9e9ed.png)

**Comment by tomasmcguinness** [comment]
In the most recent versions of the library (v3+) I've changed how the certificates are provided. The library is no longer responsible for opening them. Instead, you must provide them. I recommend upgrading to the latest version to see if this helps? I'm aware of memory leaks issues and other problems with X509Certificate classes. 

Could you try the newer versions and see if that helps?

**Comment by olegmedv** [comment]
> Could you try the newer versions and see if that helps?
Thank you for the answer! I already update it few months ago) It works! You are great)))

**Comment by tomasmcguinness** [comment]
Fantastic! I'll go ahead and close this issue.
