### ISSUE TITLE
This was working for us but stopped working.

### ISSUE THREAD

**Issue by brallierc** [tomasmcguinness/dotnet-passbook#149]
I have tried the latest nuget package. I have went through step by step on your instructions. We can generate the pkpass but when I run it through your validation tool it says its not signed by apple. I am not sure if there are new required fields. I am not sure if we should still use the apple certificate that you mention expiring in 2023. We have spent weeks trying to fix this.

Any thoughts?

**Comment by tomasmcguinness** [comment]
I've updated the readme to indicate the G4 WWDR certificate is now required.
