### ISSUE TITLE
"Cannot load app details"  Error in back of the pass

### ISSUE THREAD

**Issue by shane2201** [tomasmcguinness/dotnet-passbook#151]
I am getting "Cannot load app details"  Error in back of the pass. 
can anyone please help me on this
![backpass](https://user-images.githubusercontent.com/72590105/159618658-823a3fd2-17e3-4bf9-8ace-508828d79ae4.jpg)
?

**Comment by tomasmcguinness** [comment]
Are you using the correct bundle identifier? Has the app been submitted to the store yet?

**Comment by shane2201** [comment]
Yes, we are using the correct bundle identifier and the app is also submitted to the app store. 
Is there a way to hide this?

**Comment by tomasmcguinness** [comment]
Is the app owned by the same Apple account that you are using to generate the Passkit certificates from?

**Comment by KiwiVandi** [comment]
I find/found that if running in simulator I encounter this error also, but running from device solves it :)

**Comment by KiwiVandi** [comment]
Im also on Pitt st sydney if you need help haha

**Comment by tomasmcguinness** [comment]
I'm going to close this ticket. If there is still an issue, just reopen it.
