### ISSUE TITLE
[QUESTION] 'Certificate could not be found'

### ISSUE THREAD

**Issue by angelru** [tomasmcguinness/dotnet-passbook#163]
`Certificate could not be found. Please ensure the thumbprint and cert location values are correct.`

I am testing the library, at the moment no PassbookCertificate or AppleWWDRCACertificate has been provided, without this it is impossible to generate a .pkpass to view it on android?

**Comment by tomasmcguinness** [comment]
Sorry, my library will only work when the Apple certificates are provided.

**Comment by angelru** [comment]
Thanks, another question, if you sign with another non-apple PKCS7, does the generated pkpass work on iOS?

**Comment by tomasmcguinness** [comment]
I don't believe so.

**Comment by angelru** [comment]
Thanks!
