### ISSUE TITLE
Getting System.Security.Cryptography.CryptographicException when iam trying to generate a PKPass file

### ISSUE THREAD

**Issue by Mazhar9797** [tomasmcguinness/dotnet-passbook#169]
An exception of type 'System.Security.Cryptography.CryptographicException' occurred and was caught.
Message : Keyset does not exist
Source : System.Security
Data : System.Collections.ListDictionaryInternal
TargetSite : CMSG_SIGNER_ENCODE_INFO CreateSignerEncodeInfo(System.Security.Cryptography.Pkcs.CmsSigner, Boolean, System.Security.Cryptography.SafeCryptProvHandle ByRef)

When i test it in my machine it works fine but when moved to Server its giving this error.
- Tried providing the permission to the IUSR - didnt work
-  Checked with private key it does exists

Below is the code iam using:
request.CertThumbprint = "xxxx"
                request.CertLocation = System.Security.Cryptography.X509Certificates.StoreLocation.LocalMachine;
            

                var pkPassCert = "yyyy"
                if (pkPassCert.Contains("~"))
                {
                    pkPassCert = System.Web.HttpContext.Current.Server.MapPath(pkPassCert);
                }
                var wwdrcert = File.ReadAllBytes(pkPassCert); 
                request.AppleWWDRCACertificate = wwdrcert;

            
                request.Style = PassStyle.EventTicket;

                generatedPass = generator.Generate(request);

**Comment by tomasmcguinness** [comment]
So you're using IIS for hosting your code?

**Comment by Mazhar9797** [comment]
yes ....the code is moved through the Azure devops pipeline

**Comment by tomasmcguinness** [comment]
Is it deployed to a virtual machine or similar in Azure? 

The latest version of dotnet-passbook no longer uses CertThumbprint and CertLocation because of issues like these.

Can you create an instance of an X509Certificate using your own pass (like you do with the WWDR certificate?

**Comment by Mazhar9797** [comment]
this code has been moved to 3 different servers and its works fine there with the same certificate but the issue is only in the 4th server were this error is coming. In all service running on IIS 
Have used the same code in all servers

**Comment by Mazhar9797** [comment]
Sorry my bad we got it resolved buy giving the IIS_IUSRS required permissions in the Private key section , before we had tried with the wrong user. Thanks for ur support
One more think wanted to know is there any way using which we can view the generated pass in WINDOWS machine ?, have checked online tools but cudnt find one

**Comment by tomasmcguinness** [comment]
No, not I know of, sorry. A web visualiser is something that might be very useful.
