### ISSUE TITLE
Error: Passbook.Generator.Exceptions.ManifestSigningException: Failed to sign manifest ---> System.DllNotFoundException: crypt32.dll   at Interop+Crypt32.CryptEncodeObject (Interop+Crypt32+MsgEncodingType dwCertEncodingType, Interop+Crypt32+CryptDecodeObjectStructTyp

### ISSUE THREAD

**Issue by XamTechie** [tomasmcguinness/dotnet-passbook#173]

**Comment by XamTechie** [comment]
I am generating the pass using xamarin.IOS having below configuration

 X509KeyStorageFlags flags = X509KeyStorageFlags.MachineKeySet | X509KeyStorageFlags.Exportable;
                X509Certificate2 developerCertificate = new X509Certificate2(NSBundle.MainBundle.PathForResource("pass", "p12"), "mypassword",flags);
                X509Certificate2 appleWWDRCA = new X509Certificate2(NSBundle.MainBundle.PathForResource("AppleWWDRCAG4", "cer"),"",flags);
                request.AppleWWDRCACertificate = appleWWDRCA;
                request.PassbookCertificate = developerCertificate;

**Comment by tomasmcguinness** [comment]
Hi,

My library uses bouncy castle under the covers to sign the manifest. I'm not sure if that's portable onto iOS. A quick Google suggests that crypt32.dll is Windows only.

Has your code worked before?

Tom

**Comment by tomasmcguinness** [comment]
Hmmm, I know there is a Portable version of bouncy castle that should work with Xamarin. It might be worth pulling down the source code and trying with that version instead?

**Comment by tomasmcguinness** [comment]
Sorry I don't use Bouncy Castle anymore. I just had a look at my solution code. The signing is done by a .Net library.

The exception you posted states that crypto32.dll can't be found. I suspect very much this is a platform issue. I'm guessing that System.Security.Cryptography.Pkcs has some windows dependencies.

**Comment by XamTechie** [comment]
System.Security.Cryptography.Pkcs doen't supports mono .. bouncy castle can ..😕

**Comment by 007vel** [comment]
I am facing the same issue:
Passbook.Generator.Exceptions.ManifestSigningException: Failed to sign manifest ---> System.DllNotFoundException: crypt32.dll

Any solution for xamarin iOS?

**Comment by tomasmcguinness** [comment]
At present, no. The library I use isn't available on Xamarin. Might I ask why you are generating the actual pass on the app? This means you would be embedding the private key in your app. Could you not generate the pass on a webserver?

**Comment by 007vel** [comment]
In my case, I am trying to generate a pass within a mobile app. I am thinking about why we need to generate it on web server. 
So, I thought of using the .net library in xamarin project because both are .net platforms. Initially, everything is good with the library, then finally end up with this issue.

- I embedding the private key

**Comment by tomasmcguinness** [comment]
Okay. The cryptographic library used within the code just doesn't work on mono, so I'm afraid I cannot help any further. @XamTechie mentioned that bouncy castle does work on Mono, so you might be able to modify the library.

**Comment by XamTechie** [comment]
@tomasmcguinness  @007vel   I found the workaround , I have shifted the pass generating code from mobile to backend API .. and its as a charm. and consuming this API in mobile and aad the pass to the wallet.

**Comment by tomasmcguinness** [comment]
Perfect - I think that's better overall, since you retain control of the private key. I'm going to close this ticket now.

**Comment by XamTechie** [comment]
@007vel  But I am not able to call the Wallet app directly from my app.. 🤯

**Comment by tomasmcguinness** [comment]
If you want to give it a try, you can always modify the code and use the portable version of bouncy castle?
