### ISSUE TITLE
Pass not downloading using ASP.NET MVC

### ISSUE THREAD

**Issue by AC-90** [tomasmcguinness/dotnet-passbook#174]
I am following the example provided in the code, trying to get a pass downloaded on a ASP.NET page. I have provided all the values required for a generic pass but cannot seem to get the pass to download. Would you have any idea why the pass is not downloading?

![image](https://user-images.githubusercontent.com/116019159/196228264-a6d33e4f-5f5e-4c40-9da6-57b75ca680a6.png)

**Comment by tomasmcguinness** [comment]
What do you mean by "cannot get the pass to download? Do you get an error on iOS saying the pass could not be opened?

**Comment by AC-90** [comment]
I'm running the above in VS on a windows machine, and can see the pass being setup. When it comes to downloading the pass, nothing downloads?

**Comment by eimantas** [comment]
The code you're using is assigning a `FileContentResult` to a variable. What type of interface do you have for the download? Swagger? How are you passing the `Result` variable to something else?

**Comment by AC-90** [comment]
Thank you both for your help, the issue has been resolved. The content type and header was not being set correctly.
