### ISSUE TITLE
Int overflow in associated store identifiers?

### ISSUE THREAD

**Issue by eimantas** [tomasmcguinness/dotnet-passbook#179]
I am trying to sign a pass that contains a particular app store app id around `6444824880` and I get the runtime error that bytes in json cannot be converted to `int`. I then try to hardcode the value of the id into the code and I get the compile time error stating that it cannot convert `long` to `int`:

```
AssociatedStoreIdentifiers = new() { 6444824885 }, // the number is underlined with error about conversion
```

It would make sense to either change the `List<int>` to either unsigned, long or string altogether.

**Comment by tomasmcguinness** [comment]
Ah, thanks. I'll switch it over to a long.

**Comment by tomasmcguinness** [comment]
Hi. I've changed that and it should be available once version 3.2.3 finishes nuget package validation.

**Comment by eimantas** [comment]
Something's not right. The associated app identifier overflows somewhere. The generated snippet in pass.json looks like this:

```json
  "associatedStoreIdentifiers": [
    -2145109708
  ],
```

**Comment by tomasmcguinness** [comment]
Aggg, there was a cast during the serialization! That's fixed now (I've also added a test condition) and version 3.2.4 is pushed to Nuget.

**Comment by eimantas** [comment]
All good now. Thanks!
