### ISSUE TITLE
Strip image not showing 

### ISSUE THREAD

**Issue by ahmadbjanthala** [tomasmcguinness/dotnet-passbook#180]
Hello 

im using this code for the icons and images and it works for the icon and the logo but it not showing the strip

            PassGenerator generator = new();
            PassGeneratorRequest request = new();
            request.Style = PassStyle.EventTicket;

            request.Images.Add(PassbookImage.Icon, File.ReadAllBytes(Path.Combine(Directory.GetCurrentDirectory(), "Assets/Icon.png")));
            request.Images.Add(PassbookImage.Strip, File.ReadAllBytes(Path.Combine(Directory.GetCurrentDirectory(), "Assets/Strip.png")));
            request.Images.Add(PassbookImage.Logo, File.ReadAllBytes(Path.Combine(Directory.GetCurrentDirectory(), "Assets/Logo.png")));

**Comment by tomasmcguinness** [comment]
If you change the pass style to a store card, for example, does the strip appear?

Strip works in event ticket, but doesn't work if you have background or thumbnail images specified.
