### ISSUE TITLE
Failed to Sign Manifest

### ISSUE THREAD

**Issue by osbash** [tomasmcguinness/dotnet-passbook#181]
We've been using this package for a little under a year and our apple certificate recently expired.

After generating a new certificate and following the instructions found here: **https://github.com/tomasmcguinness/dotnet-passbook/blob/master/using-openssl.md**

A new certificate was generated and replaced the existing one as well as downloading the G4 version of AppleWWDRCA.  When running this locally, everything works fine.  As soon as this is pushed to our production server, a "Failed to sign Manifest" error is thrown with no additional details.

I can confirm that the Pass Identifier, Team Identifier and Password are all correct.

The only thing that I did notice is when I run the working .pkpass (generated locally) through the pkpassvalidator everything passes except "PassTypeIdentifier in signature matches value in pass.json"

Any thoughts on this?

**Comment by tomasmcguinness** [comment]
Hi,

If it’s failing in production, perhaps you haven’t included the private key in the certificate? This might be available locally, but not remotely.

Have you changed anything in your server setup? How are you hosting it?

Regards,
Tom

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: Sam ***@***.***>
Sent: 15 May 2023 23:19
To: ***@***.***>
Cc: ***@***.***>
Subject: [tomasmcguinness/dotnet-passbook] Failed to Sign Manifest (Issue #181)


We've been using this package for a little under a year and our apple certificate recently expired.

After generating a new certificate and following the instructions found here: https://github.com/tomasmcguinness/dotnet-passbook/blob/master/using-openssl.md

A new certificate was generated and replaced the existing one. When running this locally, everything works fine. As soon as this is pushed to our production server, a "Failed to sign Manifest" error is thrown with no additional details.

I can confirm that the Pass Identifier, Team Identifier and Password are all correct.

The only thing that I did notice is when I run the working .pkpass (generated locally) through the pkpassvalidator everything passes except "PassTypeIdentifier in signature matches value in pass.json"

Any thoughts on this?

**Comment by tomasmcguinness** [comment]
Closing this as I haven't heard anything back. If you have more information, please reopen the ticket.
