### ISSUE TITLE
How to generate custom passes?

### ISSUE THREAD

**Issue by Rigo09** [tomasmcguinness/dotnet-passbook#184]
Hello @tomasmcguinness, I'm working for the first time on a development that involves the generation of digital passes for iOS Wallet from a Blazor Web Server API and I tried your library and it's working very well, I already managed to generate a first event-type pass, excellent work .

But I have a question regarding how customizable a pass can be. I read the documentation that is in the apple developer guide and it explains that only 5 types of passes can be generated, but I have the following question: How can you generate a pass design like credit cards or this type of pass for example:

student ID cards in Wallet
![image](https://github.com/tomasmcguinness/dotnet-passbook/assets/37517852/7b2b71c7-e662-4ad2-9649-4a2ca925acb2)

Based on your experience, do you happen to know how these types of passes work?

**Comment by singhdilip1007** [comment]
@tomasmcguinness 
I've to generate one more row at red boxes places, can help me out  how we can?

<img width="541" alt="Dummy" src="https://github.com/tomasmcguinness/dotnet-passbook/assets/18436894/027415c2-f958-4c0e-b9db-3e96312ed62a">

**Comment by tomasmcguinness** [comment]
> Hello @tomasmcguinness, I'm working for the first time on a development that involves the generation of digital passes for iOS Wallet from a Blazor Web Server API and I tried your library and it's working very well, I already managed to generate a first event-type pass, excellent work .
> 
> 
> 
> But I have a question regarding how customizable a pass can be. I read the documentation that is in the apple developer guide and it explains that only 5 types of passes can be generated, but I have the following question: How can you generate a pass design like credit cards or this type of pass for example:
> 
> 
> 
> student ID cards in Wallet
> 
> ![image](https://github.com/tomasmcguinness/dotnet-passbook/assets/37517852/7b2b71c7-e662-4ad2-9649-4a2ca925acb2)
> 
> 
> 
> Based on your experience, do you happen to know how these types of passes work?
> 
> 

Hi,

Sorry I haven't replied to this yet!!

You might need to generate a custom strip image, that includes the background and headshot.

Tom

**Comment by tomasmcguinness** [comment]
> @tomasmcguinness 
> 
> I've to generate one more row at red boxes places, can help me out  how we can?
> 
> 
> 
> <img width="541" alt="Dummy" src="https://github.com/tomasmcguinness/dotnet-passbook/assets/18436894/027415c2-f958-4c0e-b9db-3e96312ed62a">
> 
> 

The number of fields and their positions is controlled by iOS. 

It lays them out automatically.

Have you tried adding auxiliary fields?

**Comment by singhdilip1007** [comment]
@tomasmcguinness 
Thanks for your reply, but I couldn't understand how to add auxiliary fields`. Below is my current snippet and if you can help, it will be great for me


                request.AddSecondaryField(new StandardField("BT", "IN", "12312"));
                request.AddSecondaryField(new StandardField("PPT", "IC", "3113"));
                request.AddSecondaryField(new StandardField("GT", "IG", "45"));
                request.AddSecondaryField(new StandardField("MT", "IM", "4502"));

**Comment by Rigo09** [comment]
Hola @singhdilip1007  yo agrego campos auxiliares de la siguiente manera:

` var pass = new PassGeneratorRequest
 {
     PassTypeIdentifier = "your.pass.identifier",
     SerialNumber = Guid.NewGuid().ToString("N"),
     TeamIdentifier = "yourTeamIdentifier ",
     OrganizationName = "Membresía Club Hondureño Árabe",
     Description = "Membresía Club Hondureño Árabe",
     LogoText = "Club Hondureño Árabe",
     ForegroundColor = "#cfc8b5",
     BackgroundColor = "#161616",
     LabelColor = "#f0faf9",
     RelevantDate = DateTime.UtcNow,
     AppleWWDRCACertificate = appleWWDRCA,
     PassbookCertificate = certificate,
     Style = PassStyle.Generic
 };

 var primaryField = new StandardField("Nombre", "Socio", nombre);

 var secundaryField = new StandardField("Codigo", "Código", codigo);
 var AuxiliaryFields = new StandardField("ID", "ID", Identidad);
 var AuxiliaryFields2 = new StandardField("Estatus", "Estatus", estado);

pass.AddPrimaryField(primaryField);
pass.AddSecondaryField(secundaryField);
pass.AuxiliaryFields.Add(AuxiliaryFields);
pass.AuxiliaryFields.Add(AuxiliaryFields2);
`

**Comment by singhdilip1007** [comment]
@Rigo09 thanks for help, can help me again about how we can add 3 items in a rows ?
Actually I've to generate 4 rows and 3/4 fields in each rows.

Thanks in advance @Rigo09 @tomasmcguinness

**Comment by tomasmcguinness** [comment]
You cannot control the number of items per row directly.

I suggest adding three Secondary Items and three Auxiliary Items and see what it looks like.

**Comment by singhdilip1007** [comment]
@Rigo09 @tomasmcguinness 

Below is my code nC# code snippet:
```C#
   request.AddSecondaryField(new StandardField("UT", "Code", "0110518"));
                request.AddSecondaryField(new StandardField("PT", "ID", "Generic"));
                request.AddSecondaryField(new StandardField("GGT", "Status", "Inprocess"));
                request.AddSecondaryField(new StandardField("MT", "Name", "Team"));

                request.AddAuxiliaryField(new StandardField("PST", "PD", "10.15"));
                request.AddAuxiliaryField(new StandardField("QST", "QD", "30"));
                request.AddAuxiliaryField(new StandardField("DDST", "AD", "All"));
                request.AddAuxiliaryField(new StandardField("DSST", "DS", "Tabroc"));

```
and below is my output

<img width="527" alt="11Untitled11" src="https://github.com/tomasmcguinness/dotnet-passbook/assets/18436894/0b43fc60-54b7-405b-8792-ed033d3105ee">


I'm just looking to add on more row. Can consider below line mentioned on their docs.
`Coupon, store cards, and generic cards with square barcodes can contain up to 4 secondary and ancillary fields in total.`

PLease guide me

**Comment by tomasmcguinness** [comment]
I'm not sure you can do any more than that. 

Could you add some fields to the back?

**Comment by tomasmcguinness** [comment]
I'm closing this issue as I haven't had a reply. If you want to continue, you can reopen this ticket. Thx.
