### ISSUE TITLE
Pass Updates

### ISSUE THREAD

**Issue by tomm3w** [tomasmcguinness/dotnet-passbook#187]
I know that information can be updated on the front of the pass if you have "Automatic Updates" turned on. Two questions, first, if it is turned on, is there a setting for speeding up the data transfer to the pass to update current miles, or value if creating a gift card, and second, Is there a way to "auto updates" if the window is not showing that option but it can be set up in the backend to lock user out from closing.

3rd, I would like to set up a private conversation with you to discuss a major issue.  I purchased your platform from you  a few years back.

Thanks
Tom Griffin

**Comment by tomasmcguinness** [comment]
As I've not heard from you, I'm going to close this ticket.

**Comment by tomm3w** [comment]
Tomas, in an email you had said you did not have time to work with me, has that changed at all.  I could use some help from someone who knows your platform well.  If not you, maybe you have a contact from the past.  
Thanks
Tom
