### ISSUE TITLE
PrimaryFileds more than one

### ISSUE THREAD

**Issue by AlexanderKrustev** [tomasmcguinness/dotnet-passbook#188]
Hello currently i cannot add more than one PrimaryField. Anyone with a similar problem?

**Comment by tomasmcguinness** [comment]
Do you mean the fields don't show on the pass or you get an error?

**Comment by AlexanderKrustev** [comment]
Oh, sorry. I am trying to generate a Generic Pass. Currently, i can add Field to the PrimaryField collection, and it looks fine in the request. However, on the pass only one field could be visible

**Comment by tomasmcguinness** [comment]
For generic passes, I beleive you can only have one primary field. My library doesn't check the type of quantity of the fields. 

https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/Creating.html

Check Figure 4-5

<img width="533" alt="image" src="https://github.com/tomasmcguinness/dotnet-passbook/assets/302741/e48c0471-7a46-497f-9805-68b3e0e77dad">
