### ISSUE TITLE
WebserviceUrl can not add

### ISSUE THREAD

**Issue by SanelS** [tomasmcguinness/dotnet-passbook#189]
WriteStandardKeys do not set WebserviceURL

**Comment by tomasmcguinness** [comment]
You need to set both the url and authentication token.

**Comment by SanelS** [comment]
Thank you very much! On Nov 25, 2023, at 11:34 AM, Tomas McGuinness ***@***.***> wrote: You need to set both the url and authentication token. — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: ***@***.***>

**Comment by tomasmcguinness** [comment]
You're welcome! If you find this library useful, please consider supporting me https://www.buymeacoffee.com/fmkj2nnq3?l=en
