### ISSUE TITLE
Problem with Updating dotnet-passbook to latest version

### ISSUE THREAD

**Issue by cgill1607** [tomasmcguinness/dotnet-passbook#190]
Hello,

I'm working with dotnet passbook Version 2.0.6.
It works like a charme :-) !

Now i want to update the nuget package of passbook to the latest version. 3.2.4

After the Update in the  PassGeneratorRequest class i have missing Properties
request.Certificate
request.CertificatePassword
and 
request.AppleWWDRCACertificate needs an X509Certificate2 instead of a byte[]

It seems that you have shifted from the direct binary data stored in the .PFX and .cer files to some internal certificate structure.

for the 2.0.6 i've read the binary data created from windows PC, transfered the content of the PFX and .CER files to my PostgreSql server database and use the binary data retrieved from the database to feed request.certificate and AppleWWDRCACertificate in my ubuntu linux server environment which creates passes.

Now my question. What ist the best way to get an x509certificate instance witrh the binary data from my database?

With kind regards

Dr. Christian Gill

**Comment by tomasmcguinness** [comment]
Hi,

You can use the same binary to create your own instance of an X509Certificate and provide passwords as necessary.

Under the covers, that is what my library was doing anyway.

I hope that helps.
