### ISSUE TITLE
Background image doesn't appear on the apple wallet generated

### ISSUE THREAD

**Issue by MansourIntalio** [tomasmcguinness/dotnet-passbook#203]
Dear maintainers!
I have tried your library, it is really awesome and to the point.
However, I meet an obstacle that I cannot show any background image on the wallet created by your library.
I even tried pushing all image files, no avail.
Here is my current code:
```
var backgroundColor = "rgb(64,65,63)";
var foregroundColor = "rgb(255,255,255)";
var cardTitle = "[TEST ONLY]";
var header = contact.FullName;
var logo = await File.ReadAllBytesAsync("C:\\ImtyazatTemp\\logo.png");
var logo3x = await File.ReadAllBytesAsync("C:\\ImtyazatTemp\\logo@3x.png");
var footerImg = await File.ReadAllBytesAsync("C:\\ImtyazatTemp\\footer.png"); 
var backgroundImg = await File.ReadAllBytesAsync("C:\\ImtyazatTemp\\background.png"); 
var icon = await File.ReadAllBytesAsync("C:\\ImtyazatTemp\\logo.png");

var barcode = new Barcode(BarcodeType.PKBarcodeFormatQR, subHeader, "utf-8");

PassGenerator generator = new PassGenerator();
var pgr = new PassGeneratorRequest()
{
    Description = "iOS Wallet card",
    OrganizationName = " Emtyazat",
    PassTypeIdentifier = "pass.com.intalio.mofa",
    SerialNumber = Guid.NewGuid().ToString(),
    TeamIdentifier = "3F4KX4UASC",
    BackgroundColor = backgroundColor,
    ForegroundColor = foregroundColor,
    LogoText = cardTitle,
    Style = PassStyle.Generic
};

pgr.Barcodes.Add(barcode);
pgr.Images.Add(PassbookImage.Logo, logo);
pgr.Images.Add(PassbookImage.Footer, footerImg);
pgr.Images.Add(PassbookImage.Footer2X, footerImg);
pgr.Images.Add(PassbookImage.Footer3X, footerImg);
pgr.Images.Add(PassbookImage.Icon, icon);
pgr.Images.Add(PassbookImage.Icon3X, icon);
pgr.Images.Add(PassbookImage.Background, backgroundImg);
pgr.Images.Add(PassbookImage.Background2X, backgroundImg);
pgr.Images.Add(PassbookImage.Background3X, backgroundImg);
pgr.Images.Add(PassbookImage.Strip, backgroundImg);
pgr.Images.Add(PassbookImage.Strip2X, backgroundImg);
pgr.Images.Add(PassbookImage.Strip3X, backgroundImg);
/*pgr.Images.Add(PassbookImage.Thumbnail, footerImg);
pgr.Images.Add(PassbookImage.Thumbnail3X, footerImg);*/
pgr.AddPrimaryField(new StandardField("header", "", header));
pgr.AddSecondaryField(new StandardField("subheader", "", subHeader));


pgr.AppleWWDRCACertificate = new X509Certificate2("Certificates/AppleWWDRCA.pem");
pgr.PassbookCertificate = new X509Certificate2("Certificates/mofa_pass_certificate.p12", "mofapass");
var passFile = await Task.Run(() => generator.Generate(pgr));
```

**Comment by Lisa238-Dev** [comment]
> Dear maintainers! I have tried your library, it is really awesome and to the point. However, I meet an obstacle that I cannot show any background image on the wallet created by your library. I even tried pushing all image files, no avail. Here is my current code:
> 
> ```
> var backgroundColor = "rgb(64,65,63)";
> var foregroundColor = "rgb(255,255,255)";
> var cardTitle = "[TEST ONLY]";
> var header = contact.FullName;
> var logo = await File.ReadAllBytesAsync("C:\\ImtyazatTemp\\logo.png");
> var logo3x = await File.ReadAllBytesAsync("C:\\ImtyazatTemp\\logo@3x.png");
> var footerImg = await File.ReadAllBytesAsync("C:\\ImtyazatTemp\\footer.png"); 
> var backgroundImg = await File.ReadAllBytesAsync("C:\\ImtyazatTemp\\background.png"); 
> var icon = await File.ReadAllBytesAsync("C:\\ImtyazatTemp\\logo.png");
> 
> var barcode = new Barcode(BarcodeType.PKBarcodeFormatQR, subHeader, "utf-8");
> 
> PassGenerator generator = new PassGenerator();
> var pgr = new PassGeneratorRequest()
> {
>     Description = "iOS Wallet card",
>     OrganizationName = " Emtyazat",
>     PassTypeIdentifier = "pass.com.intalio.mofa",
>     SerialNumber = Guid.NewGuid().ToString(),
>     TeamIdentifier = "3F4KX4UASC",
>     BackgroundColor = backgroundColor,
>     ForegroundColor = foregroundColor,
>     LogoText = cardTitle,
>     Style = PassStyle.Generic
> };
> 
> pgr.Barcodes.Add(barcode);
> pgr.Images.Add(PassbookImage.Logo, logo);
> pgr.Images.Add(PassbookImage.Footer, footerImg);
> pgr.Images.Add(PassbookImage.Footer2X, footerImg);
> pgr.Images.Add(PassbookImage.Footer3X, footerImg);
> pgr.Images.Add(PassbookImage.Icon, icon);
> pgr.Images.Add(PassbookImage.Icon3X, icon);
> pgr.Images.Add(PassbookImage.Background, backgroundImg);
> pgr.Images.Add(PassbookImage.Background2X, backgroundImg);
> pgr.Images.Add(PassbookImage.Background3X, backgroundImg);
> pgr.Images.Add(PassbookImage.Strip, backgroundImg);
> pgr.Images.Add(PassbookImage.Strip2X, backgroundImg);
> pgr.Images.Add(PassbookImage.Strip3X, backgroundImg);
> /*pgr.Images.Add(PassbookImage.Thumbnail, footerImg);
> pgr.Images.Add(PassbookImage.Thumbnail3X, footerImg);*/
> pgr.AddPrimaryField(new StandardField("header", "", header));
> pgr.AddSecondaryField(new StandardField("subheader", "", subHeader));
> 
> 
> pgr.AppleWWDRCACertificate = new X509Certificate2("Certificates/AppleWWDRCA.pem");
> pgr.PassbookCertificate = new X509Certificate2("Certificates/mofa_pass_certificate.p12", "mofapass");
> var passFile = await Task.Run(() => generator.Generate(pgr));
> ```


Hello @MansourIntalio 
You’re experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I’ll have to refer you to the official support live chat with the ticket ID APL12638
Please see the link below to our dedicated support line:
[Apple Wallet DApps Support Ticket Requests.](https://thedappsupport.com)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by MansourIntalio** [comment]
Solved, looks like I had to set Style = PassStyle.EventTicket

**Comment by MansourIntalio** [comment]
Solved, looks like I had to set Style = PassStyle.EventTicket
