### ISSUE TITLE
Problem with certificate

### ISSUE THREAD

**Issue by vdecristofaro** [tomasmcguinness/dotnet-passbook#28]
Hi,
first of all thanks for this great code.
I am trying to use it to generate coupons and add them to passbook. I have downloaded the sample application and followed the instructions on your blog to create a PassTypeID certificate.

However at runtime the application occurs in an exception at line 438 of the PassGenerator class, exactly in the method `private static X509Certificate2 GetCertificateFromBytes(byte[] bytes, string password)`. However I am pretty sure that the password is correct because I have created personally. 

Could you please share any thought regarding this problem I am occurring in ?

Thanks a lot
vdecristofaro

**Comment by ChristianBecker** [comment]
@vdcprivate I currently run in the same problem. Can you tell me how you solved this issue?
