### ISSUE TITLE
The APPLE_CERTIFICATE_THUMBPRINT in PassGenerator is wrong

### ISSUE THREAD

**Issue by richRubie** [tomasmcguinness/dotnet-passbook#36]
The thumbprint as an invisible character at the beginning.

http://stackoverflow.com/questions/8448147/problems-with-x509store-certificates-find-findbythumbprint

**Comment by aelm** [comment]
I noticed this too. It is still present with the most recent update to the APPLE_CERTIFICATE_THUMBPRINT const value in PassGenerator.cs.

**Comment by joe-keane** [comment]
PR in place with this solved.
