### ISSUE TITLE
dotnet-passbook.0.9.7.nupkg has issues generating the passbook

### ISSUE THREAD

**Issue by richRubie** [tomasmcguinness/dotnet-passbook#37]
It appears that there is an issue with bouncy castle. Using the current GitHub version seems to work fine.

**Comment by tomasmcguinness** [comment]
Unfortunately, I don't keep NuGet up-to-date with the code. I'll be updating the project to bring it up to iOS 10, so expect an updated NuGet package soon.

**Comment by tomasmcguinness** [comment]
Nuget package is now at version 1.0.
