### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by wilmerferreira** [tomasmcguinness/dotnet-passbook#38]
Hello Tomas,

I'm working with the passbook project and we're are using your project.

We saw in the Apple Developer Guide that the passbook files supports localization but we couldn't find how can we do that with your package. Can you give us a clue?

- Apple Developer Guide: Passes Support Localization
https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/PassKit_PG/Creating.html#//apple_ref/doc/uid/TP40012195-CH4-SW54

**Comment by tomasmcguinness** [comment]
Hello,

Unfortunately, dotnet-passbook doesn't support the localization features in Passbook. This is one of the reasons the library never reached 1.0 status.

Sorry I can't be of more help.

Regards,

**Comment by joe-keane** [comment]
Hi,

request.AddLocalization is the key for that issue.
I'm currently using it on a live project and it's working as expected with 7 languages.

**Comment by joe-keane** [comment]
Small sample with a single property:
request.Description = "boarding_pass";
....
var labelKeys = new List<string> { "boarding_pass"}; //all the keys
foreach (string lang in GetSupportedLangs())
{
    foreach (string key in labelKeys)
    {
        request.AddLocalization(lang, key, GetLocalizedString(key, lang));
    }
}

The keys can be set as labels or values, depending on what you need to localize.

**Comment by tomasmcguinness** [comment]
It seems I merged a pull request that contains this behaviour! Thanks @joe-keane for pointing that out!! I really do need to find some time to update the Nuget package. @wilmerferreira Is that what you're after?

**Comment by wilmerferreira** [comment]
Hello guys,

Thanks for your help, now is working.
