### ISSUE TITLE
Key not valid for use in specified state during generation

### ISSUE THREAD

**Issue by cuongvo** [tomasmcguinness/dotnet-passbook#4]
Hi,

I'm having trouble generating a Passbook. 

PassGenerator.cs, SignManifestFile, at line 288:

`Org.BouncyCastle.Crypto.AsymmetricKeyParameter privateKey = DotNetUtilities.GetKeyPair(card.PrivateKey).Private;`

Is throwing an exception with `Key not valid for used in specified state` 

It's able to find the certificate for the passbook, but dies there. Any ideas? Thanks!

**Comment by spusergit** [comment]
I have the same problem. Works locally and on server getting Key not valid for use in specified state.
Can someone post a sample how to load the certificate as byte[] that resolves this issue?

**Comment by tomasmcguinness** [comment]
Are you running encountering this in an Azure Webapp? What tier of app service are you using (Free, Shared etc.)
