### ISSUE TITLE
Issue in PassGenerator.ValidateCertificates()

### ISSUE THREAD

**Issue by aelm** [tomasmcguinness/dotnet-passbook#40]
Hello and thanks for the continued support with this project. 

I noticed that the PassGenerator.ValidateCertificates() method fails when it tries to create the nameParts dictionary if the passCert.SubjectName.Name contains an organization name with a comma. e.g. O="Acme, Inc.". It throws off the split on the comma. Getting an index out of range error.

Dictionary<string, string> nameParts =
            passCert.SubjectName.Name
                .Split(new string[] { ", " }, StringSplitOptions.RemoveEmptyEntries)
                .ToDictionary(k => k.Split(new char[] { '=' }, StringSplitOptions.RemoveEmptyEntries)[0],
                    e => e.Split(new char[] { '=' }, StringSplitOptions.RemoveEmptyEntries)[1]);

Thanks.

**Comment by PavelEmelyanov** [comment]
+1

**Comment by SamuelFrankSmith** [comment]
@aelm, did you have a work-around for this?

**Comment by tomasmcguinness** [comment]
As some people have commented on this recently, I will take a look at the issue this week.

**Comment by PavelEmelyanov** [comment]
@tomasmcguinness Thanks Tomas!

**Comment by carlosjdelgado** [comment]
Hi, i just created a PR that solves it
#55 

I am doing a solution that need this, so, i'd be very gratefull if you release a version having this issue fixed.

@tomasmcguinness thanks for this wonderful library, its very useful!

**Comment by PavelEmelyanov** [comment]
@carlosjdelgado  Thanks Carlos!
