### ISSUE TITLE
DateTime fields should not be formatted with zzz

### ISSUE THREAD

**Issue by tuler** [tomasmcguinness/dotnet-passbook#42]
Two DateTime fields, ExpirationDate and RelevantDate, are being formatted with zzz, but zzz should not be used with DateTime because it does not reflect the Datime.Kind property.

https://msdn.microsoft.com/en-us/library/8kb3ddd4(v=vs.110).aspx#zzzSpecifier

"It does not reflect the value of an instance's DateTime.Kind property. For this reason, the "zzz" format specifier is not recommended for use with DateTime values."

The correct is to use the "o" standard format, which will work with DateTime or DateTimeOffset values.

https://msdn.microsoft.com/en-us/library/az4se3k1(v=vs.110).aspx#Anchor_8

**Comment by tomasmcguinness** [comment]
I've merged the pull request. Thanks!

**Comment by tuler** [comment]
Thank you very much! We have passes in multiple timezones and the RelevantDate is not correct because of that. We'll wait for a 0.9.9 release.
