### ISSUE TITLE
Not able to add pass to wallet

### ISSUE THREAD

**Issue by Shreyasramr** [tomasmcguinness/dotnet-passbook#49]
I have generated a pk pass and the same loads fine with my passviewer in MAC but the same doesn't load in my phone when I tried to add it to wallet.I tried debugging in Xcode but got the following error:Mar  1 13:05:26 ctsusers-iPhone MobileMail(PassKitCore)[273] <Notice>: Verifying structure and signature for pass <private>
Mar  1 13:05:26 ctsusers-iPhone MobileMail(PassKitCore)[273] <Fault>: Invalid data error reading pass <private>. <private>
Mar  1 13:05:26 ctsusers-iPhone MobileMail(PassKitCore)[273] <Notice>: Invalid data error reading pass <private>. <private>

but I am not able to figure out what is the problem,below I am pasting the pass.json as well.Can someone please review this and let me know what could be the problem.Appreciate your help.

{
"formatVersion": 1,
"passTypeIdentifier": "pass.com.abcd.efgh",
"authenticationToken": "PHT-jpffvctIRditg0nsmfffEFWgg56cFfdddfflvGfff50eMk",
"serialNumber": "12345784500",
"teamIdentifier": "5TKVEP484U",
"webServiceURL": "https: //services-gf.abcd.com/apiservices/passbook/",
"description": "testing Balance\\u00AE amount",
"barcode": {
"message": "3453988943989349896889368963",
"format": "PKBarcodeFormatAztec",
"messageEncoding": "iso-8859-1"
},
"organizationName": "XYZ",
"foregroundColor": "rgb(255-255-255)",
"backgroundColor": "rgb(32,95,137)",
"labelColor": "rgb(80-159-209)",
"associatedStoreIdentifiers": ["335364882"],
"locations": [],
"storeCard": {
"headerFields": [{
"key": "date",
"label": "Rx#",
"value": "201..",
"textAlignment": "PKTextAlignmentRight"
}],
"auxiliaryFields": [{
"key": "ABCD",
"label": "gegegegge",
"value": "geegeeeg"
},
{
"label": "MORE INFO",
"value": "ON BACK",
"textAlignment": "PKTextAlignmentRight"
}],
"backFields": [{
"key": "pick-up location",
"label": "PICK-UP LOCATION",
"value": "wewrwttwrtrttllllgslglskknknk "
},
{
"key": "etwr",
"label": "egegegegegeggege",
"value": "34252552525"
},
{
"key": "date",
"label": "fegegegegge",
"value": "egeggeeg"
}]
}
}

**Comment by tomasmcguinness** [comment]
I'm closing this due to its age.
