### ISSUE TITLE
How enable Lockscreen Notification?

### ISSUE THREAD

**Issue by Shadowman4205** [tomasmcguinness/dotnet-passbook#51]
Using passbook for boarding pass, what fields am i missing  to make relevant pass immediately accessible on lock screen 3 hours before departure time? ANy example?

**Comment by tomasmcguinness** [comment]
I don't have an example, but if you refer to Apple's Wallet Developer guide, it gives you information on how to make the various pass types relevant. https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/PassKit_PG/Creating.html Look at Table 4-2 for full details.
