### ISSUE TITLE
Unable to Add pass in Wallet

### ISSUE THREAD

**Issue by ac-mohan** [tomasmcguinness/dotnet-passbook#52]
Hello,

I've been trying to add a pass to my wallet, we are following all the steps from Apple developer portal and as well from your library. But, when we are try to sign the pass locally and add it to a device it works well, but when we are trying to generate a pass from your library we are facing an issue as,

> Invalid data error reading pass pass.com.***.***/7122575087. The passTypeIdentifier or teamIdentifier provided may not match your certificate, or the certificate trust chain could not be verified.

Am sure that I've set the passTypeIdentifier and teamIdentifier properly in our **pass.json**. Also have tried regenerating the pass certificate from Apple developer portal, still no progress. 

Have attached the pass.json file and the signature file and the signed .pkpass file we are generating for the same.

Can you please look at them and help me in resolving the issue? If any further details you need from my side, I'd be happy to send. Awaiting your response.

[PassFiles.zip](https://github.com/tomasmcguinness/dotnet-passbook/files/1287759/PassFiles.zip)

**Comment by ac-mohan** [comment]
@tomasmcguinness We were trying to generate the pkpass with the keychain as personal. We moved it to trusted keychain and that did the job.

Kudos to the great library _/\_

**Comment by imRanjit** [comment]
Hello @ac-mohan , I am also facing the same issue. I am not understanding how did you solved it. Can you help.

**Comment by ac-mohan** [comment]
@imRanjit 

In the code the certificate access will be initially in Current User, change that to Local Machine. This sorted out our problem.

**Comment by imRanjit** [comment]
Which code?

**Comment by tomasmcguinness** [comment]
Closing this due to the age.
