### ISSUE TITLE
Cannot find the certificate and private key for decryption

### ISSUE THREAD

**Issue by jamessuske** [tomasmcguinness/dotnet-passbook#53]
I have both certificates:

AppleWWDRCA.cer from apple

Certificates.p12 also from apple, but I added it to keychain and then selected both the certificate and private key and exported it as .p12,

This is how I implement it:

string path = (System.Web.HttpContext.Current.Server.MapPath("~/Certificates.p12"));
            byte[] certData = System.IO.File.ReadAllBytes(path);

            request.Certificate = certData;
            request.CertificatePassword = "MyPassword";

            string appleCertPath = (System.Web.HttpContext.Current.Server.MapPath("~/AppleWWDRCA.cer"));
            request.AppleWWDRCACertificate = System.IO.File.ReadAllBytes(appleCertPath);
But I get this error:

Cannot find the certificate and private key for decryption.
When I try my Certificate with .cer format (with private key, not password)

Key does not exist.
What am I doing wrong and how do I fix this?

I have confirmed that both of these files have private key with them. PLEASE HELP

**Comment by tomasmcguinness** [comment]
Hello.

P12 certificates are slightly different from Microsoft's PFX certificates. I suggest that you open the P12 certificate on a Windows PC and import it. You can then export it as a PFX file (include the private key). That should then work!

**Comment by jamessuske** [comment]
Hey! That worked, thank you very much! While I have you here....How would I attached this to an email with the Apple Wallet Logo? Just if you know off the top of your head that would be amazing and you would make my day!
