### ISSUE TITLE
Passverse.com ?

### ISSUE THREAD

**Issue by PunkStarStudios** [tomasmcguinness/dotnet-passbook#60]
Link appears to be broken. Where is it now?

**Comment by tomasmcguinness** [comment]
Hi. 

PassVerse is no longer available. I've removed mention of it from the Readme. 

May I ask why you are looking for it?

Thanks,
Tom

**Comment by PunkStarStudios** [comment]
Hey Tom.

Sure you can ask. :)

I’m in the process of building a pass server… I’ve started looking at your code base for hints and saw the mention of passverse in the readme and thought “Good gawd - a complete system ready to go … that’s a time saver if ever I’ve seen one)… wasn’t sure if passverse was one of the many services out there (that you pay per pass which wouldn’t work for me), or if it was something else that would allow me to do everything internally and independent of others.

David Brewster
Developer
Howell Data Systems Inc.
Office: 905-761-1712 ext. 2133
www.howelldatasystems.com
Proudly serving great customers for 26 years!

**Comment by tomasmcguinness** [comment]
PassVerse was (is?) a completely stand alone system. You had your own database and endpoints. It lacked many features like a pass designer, but offered an API instead. I began work on version 2 of the product, but just don't have the time to commit to finishing it.

**Comment by PunkStarStudios** [comment]
I must confess - web api programming is somewhat new to me… The last time I had to do web code was with ASP.NET under VB (hell … VS 2008? - it’s been a while)

I’m a VB6 / ObjC /C# (and xamarin - that ugly beast) / Swift guy (in that order)… primarily dealing with SQLServer and others via ADO etc and user facing stuff.

It’s taken me a few days to wrap my head around Web API coding with some basic data modelling… but it’s getting there. TO satisfy web data in the past, I just use that Parse Server platform to run my own data servers as is… but with Passkit… I needed something else (my meagre kingdom for a passkit snap-in for Parse)… so I’m sliding down the slippery slope I now find myself in.

Your code base on github is quite extensive - I am envisioning it provide some critical answers to very specific problems that will arise as I get deeper into this.

But with respect to PassVerse… perhaps a collaboration could be in the works? 
I wasn’t worried about pass designing - I was just going to have a template and do it all behind the scenes…But it sounds like ParseVerse is the piece of the puzzle that I need most. If it’s truly a plug-in system - drop in SQL links (be it connected by UDL or IP/id/pass), with places to dump in the usual configuration pieces like ApplePass AuthToken etc. If Passverse fit my needs - I could see making a pass designer UI to tie in with it to provide template files etc. I’d be willing to share that code with you in return. User UI is much more firmly planted in my comfort zone.

Your thoughts?


David Brewster
Developer
Howell Data Systems Inc.
Office: 905-761-1712 ext. 2133
www.howelldatasystems.com
Proudly serving great customers for 26 years!

**Comment by tomasmcguinness** [comment]
Hi David,

Bringing PassVerse back to life is tempting, but I just don't have the time at present. 

Thanks,
Tom
