### ISSUE TITLE
Validate Request

### ISSUE THREAD

**Issue by GiovaneLucas** [tomasmcguinness/dotnet-passbook#61]
Hi.. how to pass a valid validationHash, in the  method
`ValidateRequestHash(string passTypeIdentifier, string serialNumber, string validity, string validationHash)`
on PassbookController

the comparison `string.Equals(hash, validationHash, StringComparison.OrdinalIgnoreCase)` never is true on my debugs..

Thank you

**Comment by tomasmcguinness** [comment]
I'm closing this due to age.
