### ISSUE TITLE
No Content

### ISSUE THREAD

**Issue by PunkStarStudios** [tomasmcguinness/dotnet-passbook#62]
Hey. I thought I'd mention one line in your code should change (imho)
Status code 204 should not send back any payload. Apple will send a log message showing that's an error (and tools such as postman yell at you).

In you method 
[Route("api/v1/devices/{deviceLibraryIdentifier}/registrations/{passTypeIdentifier}/{passesUpdatedSince?}")]

Your code 
return Content<Serialization.ApiResult>(HttpStatusCode.NoContent, new Serialization.ApiResult("No updated device passes available."));

should be changed to
return ResponseMessage(new HttpResponseMessage(HttpStatusCode.NoContent));

in order to silence apple's balking at ya

**Comment by tomasmcguinness** [comment]
That's done! Thanks.
