### ISSUE TITLE
The Optional {passesUpdatedSince?} doesn't seem to work

### ISSUE THREAD

**Issue by PunkStarStudios** [tomasmcguinness/dotnet-passbook#63]
The route 
[Route("devices/{deviceLibraryIdentifier}/registrations/{passTypeIdentifier}/{passesUpdatedSince?}")]
public IHttpActionResult GetDevicePasses(string deviceLibraryIdentifier, string passTypeIdentifier, string passesUpdatedSince = null)
		
doesn't seem to work. Web client gets a 405 error back.
From what I can tell - the syntax looks correct for an option query for passesUpdatesSince is there, but I can't get it to work.
Dropping the {passesUpdatedSince} from the route does work fine of course - I just can't seem to get a route with that option string in there.

Help?

**Comment by tomasmcguinness** [comment]
Is this still an issue for you?

**Comment by tomasmcguinness** [comment]
I'm closing this due to age.
