### ISSUE TITLE
update passes

### ISSUE THREAD

**Issue by JT00** [tomasmcguinness/dotnet-passbook#64]
First of all, great library. This is really the only dot net / wallet pass integration out there. Is there any way you can provide detailed instructions for updating the passes? The pass generation/signing works excellent, however updating is also critical for me. I'm having trouble piecing together the right details based on your "updating passes" paragraph and your code.

Thanks

**Comment by tomasmcguinness** [comment]
Hi. I'm sorry for the delay in replying to this. Do you still need help?

**Comment by tomasmcguinness** [comment]
I'm going to close this now due to age.
