### ISSUE TITLE
push notification does not work

### ISSUE THREAD

**Issue by JT00** [tomasmcguinness/dotnet-passbook#65]
Everything seems to work except the push notification method. Response is never returned. Already updated firewall to allow traffic from the designated port. All certs are installed on my server.

**Comment by tomasmcguinness** [comment]
First off, have you provided a URL in your PKPass? Are you seeing any logging in iOS to indicate the push is received?

**Comment by JT00** [comment]
Yes, i did provide a url as my passes were registering with my api and pull to refresh was working. I ended up using the legacy notification format for apns binary provider vs the advanced format you provided, and it worked. For whatever reason, the advance format was hanging on the response and devices were not receiving the notification. Everything else works great. Thank you.
