### ISSUE TITLE
Error:Passbook.Generator.Exceptions.ManifestSigningException: 'Failed to sign manifest' Cryptographic key doesn't exists

### ISSUE THREAD

**Issue by RAMESHKUMAR502** [tomasmcguinness/dotnet-passbook#66]
Hi,
I have installed the Apple and pass certifacte.
When i run the code i got the below error.
Passbook.Generator.Exceptions.ManifestSigningException: 'Failed to sign manifest'
Cryptographic key doesn't exists

What could be the reason

**Comment by stancoffyn** [comment]
I'm getting this issue as well. Any updates on how to get this working?

**Comment by tomasmcguinness** [comment]
This usually means you don't have the private key as part of your certificate. Double check that's the case.

**Comment by yangzhou15** [comment]
2 possible solutions:
1. double check the thumbprint, remove leading unnoticeable characters. 
https://stackoverflow.com/questions/11115511/how-to-find-certificate-by-its-thumbprint-in-c-sharp

2. Give IIS user permission in mmc 
https://stackoverflow.com/questions/12106011/system-security-cryptography-cryptographicexception-keyset-does-not-exist

**Comment by maramusag** [comment]
> This usually means you don't have the private key as part of your certificate. Double check that's the case.

Getting same error for PassbookCertificate (Visual Studio 2022 , .net 6 asp.net core)
request.PassbookCertificate.HasPrivateKey = false;

Can this be false if .net is also having permission/access issue on the vertificate?
Or it will only be false if there is actually no private key in the cert

**Comment by tualatin** [comment]
I've got the same error, I use Visual Studio 2022 and .Net 6 asp.net core too.

`
[Error] Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred while executing the request.Passbook.Generator.Exceptions.ManifestSigningException: Failed to sign manifest---> Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The system cannot find the file specified.at Internal.Cryptography.Pal.Windows.PkcsPalWindows.GetPrivateKey[T](X509Certificate2 certificate, Boolean silent, Boolean preferNCrypt)at Internal.Cryptography.Pal.Windows.PkcsPalWindows.GetPrivateKeyForSigning[T](X509Certificate2 certificate, Boolean silent)at System.Security.Cryptography.Pkcs.CmsSignature.RSAPkcs1CmsSignature.Sign(ReadOnlySpan`1 dataHash, HashAlgorithmName hashAlgorithmName, X509Certificate2 certificate, AsymmetricAlgorithm key, Boolean silent, String& signatureAlgorithm, Byte[]& signatureValue)at System.Security.Cryptography.Pkcs.CmsSignature.Sign(ReadOnlySpan`1 dataHash, HashAlgorithmName hashAlgorithmName, X509Certificate2 certificate, AsymmetricAlgorithm key, Boolean silent, String& oid, ReadOnlyMemory`1& signatureValue)at System.Security.Cryptography.Pkcs.CmsSigner.Sign(ReadOnlyMemory`1 data, String contentTypeOid, Boolean silent, X509Certificate2Collection& chainCerts)at System.Security.Cryptography.Pkcs.SignedCms.ComputeSignature(CmsSigner signer, Boolean silent)at System.Security.Cryptography.Pkcs.SignedCms.ComputeSignature(CmsSigner signer)at Passbook.Generator.PassGenerator.SignManifestFile(PassGeneratorRequest request)--- End of inner exception stack trace ---at Passbook.Generator.PassGenerator.SignManifestFile(PassGeneratorRequest request)at Passbook.Generator.PassGenerator.GenerateManifestFile(PassGeneratorRequest request)at Passbook.Generator.PassGenerator.CreatePackage(PassGeneratorRequest request)at Passbook.Generator.PassGenerator.Generate(PassGeneratorRequest generatorRequest)at MTM.CardWebService.Services.AppleWallet.PassService.<>c__DisplayClass3_0.<GeneratePassAsync>b__0() in [...]
`

No issues with version 2.0.6, I havew to rollback at the moment. Any suggestion how to fix it?

**Comment by seth35us** [comment]
I am getting a similar error intermittently when running on Azure using version 2.0.6. I am not able to run the newer versions of Passbook Generator on Azure, using .NET 6, because of the same issue that @tualatin got above. The newer versions run fine on my local machine, but I get the @tualatin crash, when running on the server.

Since, I am not able to use the cert store in Azure, I store the key as a base64 string in my config. I then read it to a memory cache and use it. It works maybe 8 or 9 times in a row, then I intermittently get the error below. I think this is related to this error on a different site:  [#7137 ](https://github.com/OrchardCMS/OrchardCore/issues/7137#issue-708824581). 

My error is below.
```
Failed to sign manifest
Inner exception message: Keyset does not exist.
Inner inner exception message:
Stack trace: at Passbook.Generator.PassGenerator.SignManifestFile(PassGeneratorRequest request)
at Passbook.Generator.PassGenerator.GenerateManifestFile(PassGeneratorRequest request)
at Passbook.Generator.PassGenerator.CreatePackage(PassGeneratorRequest request)
at Passbook.Generator.PassGenerator.Generate (PassGeneratorRequest request)
```

This is the code using version 2.0.6. I thought that perhaps adding the certs to a memory cache would eliminate the error, but it did not. The error occurs with or without the memory cache.
```
       private readonly IMemoryCache _memoryCache;
       
       public PassHelpers(IOptionsSnapshot<AppSettings> appSettings, IMemoryCache memoryCache)
       {
            _appSettings = appSettings.Value;
            _memoryCache = memoryCache;
       }
....

        private void AddCertsToRequest(PassGeneratorRequest request, string contRoot)
        {
            var pkCacheKey = "pkCacheKey";
            if (!_memoryCache.TryGetValue(pkCacheKey, out byte[] passKitCert))
            {
                passKitCert = Convert.FromBase64String(_appSettings.PassKitCertBase64);
                _memoryCache.Set(pkCacheKey, passKitCert, new MemoryCacheEntryOptions() { AbsoluteExpiration = DateTime.Now.AddDays(1) });
            }

            request.Certificate = passKitCert;
            request.CertificatePassword = _appSettings.PassKitPassword; // The password for the certificate's private key.

            var appleCacheKey = "appleCacheKey";
            if (!_memoryCache.TryGetValue(appleCacheKey, out byte[] appleCert))
            {
                appleCert = Convert.FromBase64String(_appSettings.AppleCertBase64);
                _memoryCache.Set(appleCacheKey, appleCert, new MemoryCacheEntryOptions() { AbsoluteExpiration = DateTime.Now.AddDays(1) });
            }

            request.AppleWWDRCACertificate = appleCert;
        }
```

Here is the code that I tried with the newer versions of Passbook Generator, that works on my local machine, but not on Azure also running .NET 6. 

```
    private void AddCertsToRequest(PassGeneratorRequest request, string contRoot)
    {
        var pkCacheKey = "pkCacheKey";
        if (!_memoryCache.TryGetValue(pkCacheKey, out X509Certificate2 passKitCert))
        {
            var passKitCertByte = Convert.FromBase64String(_appSettings.PassKitCertBase64);
            passKitCert = new X509Certificate2(passKitCertByte, _appSettings.PassKitPassword);

            _memoryCache.Set(pkCacheKey, passKitCert, new MemoryCacheEntryOptions() { AbsoluteExpiration = DateTime.Now.AddDays(1) });
        }

        request.PassbookCertificate = passKitCert;

        var appleCacheKey = "appleCacheKey";
        if (!_memoryCache.TryGetValue(appleCacheKey, out X509Certificate2 appleCert))
        {
            var appleCertByte = Convert.FromBase64String(_appSettings.AppleCertBase64);
            appleCert = new X509Certificate2(appleCertByte);

            _memoryCache.Set(appleCacheKey, appleCert, new MemoryCacheEntryOptions() { AbsoluteExpiration = DateTime.Now.AddDays(1) });
        }

        request.AppleWWDRCACertificate = appleCert;
    }
```

**Comment by tomasmcguinness** [comment]
The original code in my library provide flags when creating the X509Certificate instance:

```
 X509KeyStorageFlags flags = X509KeyStorageFlags.MachineKeySet | X509KeyStorageFlags.Exportable;
X509Certificate2 certificate = new X509Certificate2(bytes, password, flags);
```

I wrote that part of the code in one of the first versions, but I recall having lots of issues in Azure myself without them.

When you create your passKitCert and appleCert instances, I recommend using the same flags.

Would you give that a try and let me know?

**Comment by seth35us** [comment]
Thanks @tomasmcguinness that worked perfectly! I am now able to use the current version of Passbook Generator on Azure.

**Comment by tomasmcguinness** [comment]
I've updated the readme with this information, so I'll close this ticket now.

**Comment by ErinDzinic** [comment]
Hello guys, 
What exactly "password" are we talking about in certificate constructor? As I am developing on Windows those passes and I only received certs from my menthors Mac, installed them on my Win and exported. I cannot understand which password do I need to put in constructor, as I am also getting "Failed to sign manifest".
Thanks

**Comment by kabuli-web** [comment]
Hey guys i's having the same issue the only thing im confused about is the password whats when i created the certificate it didnt give me any password

**Comment by WaseemAhmadGrosvenor** [comment]
> Hi,
> 
> The original code in my library provide flags when creating the X509Certificate instance:
> 
> ```
> X509KeyStorageFlags flags = X509KeyStorageFlags.MachineKeySet | X509KeyStorageFlags.Exportable;
> X509Certificate2 certificate = new X509Certificate2(bytes, password, flags);
> ```
> 
> I wrote that part of the code in one of the first versions, but I recall having lots of issues in Azure myself without them.
> 
> When you create your passKitCert and appleCert instances, I recommend using the same flags.
> 
> Would you give that a try and let me know?

Thank you, This solved my problem
