### ISSUE TITLE
"Failed to sign manifest" when selected pass cert via thumbprint.

### ISSUE THREAD

**Issue by Jyosua** [tomasmcguinness/dotnet-passbook#67]
Hi!

I followed the instructions on your blog to generate a pass certificate with a private key. I installed the Apple WWDR cert, as well. I tried installing the pass cert in both LocalMachine/Personal and CurrentUser/Personal, as well as some other stores.

I was able to have the PassGenerator automatically pick up the Apple cert, so that isn't an issue. However, no matter which store location I choose, I cannot get it to pick up my pass cert. When I instead use File.ReadAllBytes and set the CertificatePassword, it works without issue, but I don't want to commit a cert with a private key to my repository. I've double-checked my thumbprint multiple times. I'm using what is listed in windows' certificate view.

Is there some kind of bug?

    passRequest.CertThumbprint = "[thumbprint goes here]";
    passRequest.CertLocation = System.Security.Cryptography.X509Certificates.StoreLocation.LocalMachine;

**Comment by Jyosua** [comment]
Welp, found the answer to my own question. Per this [StackOverflow post](https://stackoverflow.com/questions/2609859/how-to-give-asp-net-access-to-a-private-key-in-a-certificate-in-the-certificate):

> IIS 7.5 Website is running under ApplicationPoolIdentity. Open MMC => Add Certificates (Local computer) snap-in => Certificates (Local Computer) => Personal => Certificates => Right click the certificate of interest => All tasks => Manage private key => Add IIS AppPool\AppPoolName and grant it Full control. Replace "AppPoolName" with the name of your application pool (sometimes IIS_IUSRS)

Maybe you could update the documentation to mention this for IIS users?

**Comment by tomasmcguinness** [comment]
Thanks for that. I've added it to the Readme.
