### ISSUE TITLE
Expirate Date not correctly formatted

### ISSUE THREAD

**Issue by tomasmcguinness** [tomasmcguinness/dotnet-passbook#72]
A user of dotnet-passbook contacted me via email with a pass that was not working. Once they set an Expirate Date, the pass no longer opened. It seems that my code is formatting the date incorrectly.

> "expirationDate": "2018-08-11T00:00:00",

I don't believe this is ISO 8601, so I'll investigate what's going on.

**Comment by edmistj** [comment]
@tomasmcguinness thanks for looking into this!

**Comment by tomasmcguinness** [comment]
Would you confirm what version of dotnet-passbook you are using; Nuget, or compiled directly?

**Comment by edmistj** [comment]
Using 1.0.1 from Nuget.

**Comment by tomasmcguinness** [comment]
Okay, that should contain the proper formatting code. When you set the Expiration Date, are you using a DateTimeKind.Unspecified? This can cause issues with the formatting.

**Comment by tomasmcguinness** [comment]
I've updated the RelevantDate and ExpirateDate to use DateTimeOffset instead of DateTime. Would it be possible for you to check out the code and use a compiled version of the library, rather than Nuget to check it's working okay?

**Comment by tomasmcguinness** [comment]
@edmistj Have you had an opportunity to this the code? I can  package it up into a Nuget if that would be easier for you?

**Comment by edmistj** [comment]
@tomasmcguinness sorry, we put on our annual conference this week so I was busy hosting/presenting. I'll test this next week. I can build from source to test.

**Comment by edmistj** [comment]
I'm still having issues with viewing the passes on the device. The results inside of the pass.json is now:
`"expirationDate": "2018-08-26T00:00:00-07:00"`

**Comment by edmistj** [comment]
@tomasmcguinness looks like it's working. Thanks for the update!

**Comment by tomasmcguinness** [comment]
Great! Thanks for checking. I'll add that to the Nuget package as soon as I can.

**Comment by npandrei** [comment]
I have had a similar issue with 1.0.2 from NuGet. I was able to fix it by using DateTimeKind.UTC instead of Unspecified. The DateTime variable is still DateTime, not DateTimeOffset, so the fix you are talking about does not seem to be in 1.0.2.

Thanks

**Comment by tomasmcguinness** [comment]
Sorry, but I haven't updated the Nuget package, so whilst the changes won't be in the library.
