### ISSUE TITLE
Additional Check for PK Validator

### ISSUE THREAD

**Issue by edmistj** [tomasmcguinness/dotnet-passbook#73]
Another suggestion for a check for the PK Validator.

Check that the address provided for the `WebServiceUrl` is https. If it's not the device seems to reject the pass.

**Comment by tomasmcguinness** [comment]
Agreed. It's on the roadmap!

**Comment by tomasmcguinness** [comment]
Closing this as it's being tracked in https://github.com/tomasmcguinness/pkpassvalidator/issues/1
