### ISSUE TITLE
NFC extension

### ISSUE THREAD

**Issue by HerrZwerg** [tomasmcguinness/dotnet-passbook#74]
Is there any chance for an extension with NFC? As this is currently the only way to send nfc tags, I guess this would be quite useful...

**Comment by tomasmcguinness** [comment]
Hi. I haven't add that as I've no way of testing it. If you're willing to test the behaviour works, I can certainly add it in the next couple of days.

**Comment by HerrZwerg** [comment]
Hi,

thank you very much for your fast reply. And yes of course I would like to do the testing.

Kind regards
Alfred






 BRAIN BEHIND

 ALFRED DWORSCHAK



Chief Evangelist
alfred.dworschak@brain-behind.com<mailto:alfred.dworschak@brain-behind.com>



Mobile: +43 (0)650 360 350 5
Phone: +44 (0)20 8528 1771





Von: Tomas McGuinness <notifications@github.com>
Gesendet: 19 September 2018 12:56
An: tomasmcguinness/dotnet-passbook <dotnet-passbook@noreply.github.com>
Cc: Alfred Dworschak <alfred.dworschak@brain-behind.com>; Author <author@noreply.github.com>
Betreff: Re: [tomasmcguinness/dotnet-passbook] NFC extension (#74)


Hi. I haven't add that as I've no way of testing it. If you're willing to test the behaviour works, I can certainly add it in the next couple of days.

**Comment by tomasmcguinness** [comment]
I haven't had an opportunity to look at this yet, but I plan to get around to it within the next seven days.

**Comment by tomasmcguinness** [comment]
Alfred,
I've reviewed apple's documentation and in order to make these passes work, they need to include an "Enhanced Passbook/NFC". I don't have this certificate. Do you have one?

**Comment by HerrZwerg** [comment]
Hi, just contacted Apple to upgrade our current. Will get back to you. thank you.

**Comment by tomasmcguinness** [comment]
Might I ask what terminal you're going to use for testing?

**Comment by HerrZwerg** [comment]
basically ingenico and verifone. but we also have some asian POS terminals as well. but the first two are the most important

**Comment by tomasmcguinness** [comment]
What model of Verifone terminal? This has piqued my curiosity. If Apple do approve my NFC cert, I might try and get an end-to-end solution working :)

**Comment by HerrZwerg** [comment]
We have one VX820 and one h5000 for testing purposes.

**Comment by tomasmcguinness** [comment]
Quick update. I'm waiting on an NFC reader from Flomio so I can test my changes. Hopefully I'll receive that by the end of the week. I've created a new branch from called nfc-support that contains support the nfc key and it's subkey, message. You're welcome to give that a try, but until I can test it out, I don't know if it will work!

**Comment by HerrZwerg** [comment]
Thank you very much. will check it.

**Comment by tomasmcguinness** [comment]
Been doing some digging and investigation and I've added the encryptionPublicKey property too the generator. This is required (even if the docs say it's optional - according to other sources)

**Comment by tomasmcguinness** [comment]
Tried various approaches with Apple to secure an NFC certificate to full test my changes, but without success. I have applied via the official channel, so I shall just have to wait.

I did receive my FloBLE reader and generated a pass using the Flomio app. This can be read without issue. I've open the pkpass file to inspect the contents. The message part is clear, but I'm uncertain what goes into the encryptionPublicKey field.

**Comment by HerrZwerg** [comment]
Hi,
we are currently preparing your solution to test. But I believe that the certificate from apple is the missing point. We are waiting for that.
But maybe we find something else. Thank you for your great support

**Comment by tomasmcguinness** [comment]
No problem. I'll keep this ticket updated when I have more information.

If you find dotnet-passbook to be useful, please consider buying me a coffee so I can continue to develop and support the library - buymeacoff.ee/fMKJ2NnQ3

**Comment by tomasmcguinness** [comment]
I'm going to close this issue as I cannot do any further work without the necessary certificates from Apple.
