### ISSUE TITLE
"This type of attachment" error

### ISSUE THREAD

**Issue by tomasmcguinness** [tomasmcguinness/dotnet-passbook#79]
**From @mcabriel** 

If you may, kindly check my pkpass as well as I've been trying a lot to add those in the iphone passwallet but always say, "This type of attachment can't be accessed on this device.". I tried several changes in fields and other properties of the pkpass to do some trial and error.

Already used the pkpass validator and always passed on every criteria. The certificate is new as well and will expire on 2019.

Here are some samples:

[Passbook_TestSamples.zip](https://github.com/tomasmcguinness/dotnet-passbook/files/2596339/Passbook_TestSamples.zip)

_Originally posted by @mcabriel in https://github.com/tomasmcguinness/dotnet-passbook/issues/78#issuecomment-439974058_

**Comment by tomasmcguinness** [comment]
@mcabriel Both of those passes open without issue on my iPhone.  Here is a screenshot of one of them.

![image](https://user-images.githubusercontent.com/302741/48759824-46b32900-ec9c-11e8-8b84-4db9bd52c1e6.png)

Which app are you using to try and open the files?

**Comment by mcabriel** [comment]
Hi tomasmcguinness,

Thanks for creating this as separate issue. For that specific issue, I was using iPhone 6. Trying to open those .pkpass from Safari Outlook. But seems the "Wallet" app cant read it.

**Comment by tomasmcguinness** [comment]
Okay. I'm using an iPhone 6S and the GMail app. 

Have you named your pass with the pkpass extension?

**Comment by mcabriel** [comment]
Hi @tomasmcguinness,

Yes, all files have the .pkpass extension.
I can open it now if via GMail. Thanks!

I have another questions regarding API specifically on ValidateAuthorization. Should we close this issue and reopen a new one? Or should we discuss here?

**Comment by tomasmcguinness** [comment]
That's good to hear.

For your ValidateAuthorization question, please close this issue and open another.

If you found the support useful, please consider making a donation via buymeacoff.ee/fMKJ2NnQ3. This helps me work on my dotnet-passbook and pkpassvalidator projects.

**Comment by mcabriel** [comment]
Thanks! Noted

**Comment by yangzhou15** [comment]
Thanks! I can open these 2 on my iPhone X. 
A few small tricks, 
1. the C# demo code download "Coupon" file, you need to add extension ".pkpass" to make it work. 
2. Don't skype it to your iphone, use email. You also can use "Pass2U Wallet" app to open  it on Andoird. 
3. I always got "denied" when using request.Certificate, request.CertificatePassword  and request.AppleWWDRCACertificate, instead, if I use the request.CertThumbprint and request.CertLocation, I can run the demo project successfully on localhost and download the coupon.
