### ISSUE TITLE
ValidateAuthorization Passbook Log

### ISSUE THREAD

**Issue by mcabriel** [tomasmcguinness/dotnet-passbook#80]
Hi @tomasmcguinness,
 
I checked the DB logs for the added pass on a device and found out this log below. I believe it is on ValidateAuthorization(params) method since it returns the 403 / Forbidden. But the authorizationtoken and passtype used are all correct. Do you have any thoughts on this matter?

[2018-11-20 17:01:26 +0800] Register task (for device _, pass type _, serial number _; with web service url https://url/api/passbook/) encountered error: Unexpected response code 403.

Regards,
Mark Abriel Benedicto

**Comment by mcabriel** [comment]
Do you have any way wherein you can "debug" the webservice via Visual Studio running locally while opening the pass using iPhone?

**Comment by tomasmcguinness** [comment]
There are two approaches. Firstly, you can probably debug the web app remotely, if you're hosted in Azure or similar. Just make sure you deploy a debug build. Another other approach is to run the application locally and use something like ngrok or forwardhq to create a tunnel to your local web server. Yet another approach is to run locally and use your machines IP address. You'll just need to enable HTTP support in the phone's developer settings so avoid any SSL issues.

**Comment by tomasmcguinness** [comment]
Could you provide me a copy of the pass causing you problems?

**Comment by mcabriel** [comment]
Probably the best approach for me to debug it on detailed is to run locally.
I'll check the best way to debug it on local.

Regarding the copy of the pass, same with the ones I sent to you earlier, which I attached below with more sample that has the same properties.

[Passbook_TestSamples2.zip](https://github.com/tomasmcguinness/dotnet-passbook/files/2599113/Passbook_TestSamples2.zip)

**Comment by tomasmcguinness** [comment]
Which project are you using Passbook.Web or Passbook.Sample.Web?

It's been quite a few months since I looked at this projects, so I need to remind myself of how they work.

As you mention ValidateAuthorization, are you using the same AuthorizationKey or have you changed it?

I only mention this because the authenticationToken in your pass.json starts with a period and I wouldn't have expected what with a SHA1 that was generated.

**Comment by mcabriel** [comment]
Passbook.Web specifically the PassbookV1Controller.

I changed some characters in-between from the sample authenticationToken. I'll try to generate SHA1 if that can fix the issue.

**Comment by tomasmcguinness** [comment]
Okay. So when you generated the pass, did you call the GenerateAuthorizationToken() method of the PassbookBaseController?

**Comment by mcabriel** [comment]
We have separate web and application that creates a pass "initially" using your library. The authenticationToken and webServiceUrl are also supplied.

On the API side, I have followed your approach as well.

The GenerateAuthorizationToken() will be called on the ff:
RegisterDevicePass() -> ValidateAuthorization() -> GenerateAuthorizationToken()
GetPass() -> GeneratePass() -> GenerateAuthorizationToken()

**Comment by mcabriel** [comment]
I tried to change the AuthorizationToken using a generated SHA1. Still, I'm receiving 403 / Forbidden response.

**Comment by mcabriel** [comment]
I tried to manually debug the API, I guess my issue is the generatedToken which is not equal to the authorization token. 

Regarding the "authenticationHeader.Parameter" (authorizationToken) on method ValidateAuthorization(authenticationHeader.Parameter, passTypeIdentifier.ToLower(), serialNumber), what would be the expected value for this one? Is it the AuthorizationKey we assign to the pass?

**Comment by tomasmcguinness** [comment]
It should be ApplePass <the authorization token in the pass>

**Comment by mcabriel** [comment]
Hi,

I now I understand it why the generatedToken is not equal to the authorizationToken. I'm assigning the AuthenticationToken to the AuthorizationKey which is a part of the AuthenticationToken. Which is wrong right?

My question would be, how can I generate the AuthenticationToken that I need to assign to the pass (generating a pass from a different web) based on the AuthorizationKey?


Creation of pass in another web / application:
`
            var request = GeneratePass();

            request.AuthenticationToken = ConfigurationManager.AppSettings["AuthorizationKey"].ToString();
            request.WebServiceUrl = ConfigurationManager.AppSettings["PassbookServiceUrl"].ToString();
`

API (PassbookV1Controller.cs):
`
        public IHttpActionResult RegisterDevicePass(string deviceLibraryIdentifier, string passTypeIdentifier, string serialNumber)
        {
            ValidateAuthorization(Request.Headers.Authorization, passTypeIdentifier, serialNumber);


`

PassbookBaseController.cs:
`
        private static string GenerateAuthorizationToken(string passTypeIdentifier, string serialNumber)
        {
            using (SHA1CryptoServiceProvider hasher = new SHA1CryptoServiceProvider())
            {
                byte[] data = Encoding.UTF8.GetBytes(passTypeIdentifier.ToLower() + serialNumber.ToLower() + mAuthorizationKey);
                return BitConverter.ToString(hasher.ComputeHash(data)).Replace("-", string.Empty).ToLower();
            }
        }

        private bool ValidateAuthorization(string authorizationToken, string passTypeIdentifier, string serialNumber)
        {
            String generatedToken = GenerateAuthorizationToken(passTypeIdentifier, serialNumber);
            return String.Equals(authorizationToken, generatedToken, StringComparison.OrdinalIgnoreCase);
        }

        protected String AuthorizationKey
        {
            get { return mAuthorizationKey; }
        }

        protected void ValidateAuthorization(AuthenticationHeaderValue authenticationHeader, string passTypeIdentifier, string serialNumber)
        {
            if (authenticationHeader != null &&
                string.Equals(authenticationHeader.Scheme, "ApplePass", StringComparison.OrdinalIgnoreCase) &&
                !string.IsNullOrEmpty(authenticationHeader.Parameter) &&
                !string.IsNullOrEmpty(passTypeIdentifier) &&
                !string.IsNullOrEmpty(serialNumber))
            {
                //if (ValidateAuthorization(authenticationHeader.Parameter, passTypeIdentifier.ToLower(), serialNumber))
                if (ValidateAuthorization("FECE038E9B7CB6C8F5BBD31F61261A74B9C25FAA", passTypeIdentifier.ToLower(), serialNumber))
                    return;
            }
`

**Comment by tomasmcguinness** [comment]
Okay. Glad that's sorted.

To be honest, you can generate the authorisation token in any fashion you want.

The Passbook.Web system generates it by combining three values and hashing that value.

You could just lift the 

> public  static string GenerateAuthorizationToken(string passTypeIdentifier, string serialNumber)

method and copy it into the application generating the passes. You just need to then share the "AuthorizationKey" value to ensure the hashes generated by both applications are the same. That value is essentially a shared secret.

Of course, you're free to generate and validate that token in any fashion you want, so you don't need to use my implementation if you don't want.

**Comment by mcabriel** [comment]
Thanks! I was confused between AuthorizationToken and AuthorizationKey. :D
Yes, I thought of the same thing by using your GenerateAuthorizationToken() method. 

Was already able to pass the ValidateAuthorization completely. Now having 500 status return. Maybe because of the request body (Still on the RegisterDevicePass).

Thanks again for your great support. Will close this issue now and will closely look on the current issue I'm encountering. Will might open a new one if I have questions to ask. Thanks!

**Comment by tomasmcguinness** [comment]
Great!

If you need any help, just raise another issue.
