### ISSUE TITLE
Unexpected response code 405 when removing Pass from device

### ISSUE THREAD

**Issue by mcabriel** [tomasmcguinness/dotnet-passbook#81]
Hi @tomasmcguinness ,

It seems that it can't find the "UnregisterPass" method. I double checked the routes and validated it from the apple developer site and it has the same route. Just to add, RegisterDevicePass is working properly and 100%. The HTTPDelete / Delete is also explicitly added in the customHeaders for access-control-allow-methods. With or without it, the UnregisterPass is not being invoked. Any thoughts?

It just throw this message in the Log API method when removing Pass from device.
.......................Unexpected response code 405 

        [HttpDelete]
        [Route("devices/{deviceLibraryIdentifier}/registrations/{passTypeIdentifier}/{serialNumber}")]
        public IHttpActionResult UnregisterPass(string deviceLibraryIdentifier, string passTypeIdentifier, string serialNumber)

**Comment by tomasmcguinness** [comment]
Let me have a look and report back.

**Comment by tomasmcguinness** [comment]
I'm in the process of building a new Web Service example, so I'm going to close this issue.
