### ISSUE TITLE
Question: API methods GetPass and GetDevicePasses

### ISSUE THREAD

**Issue by mcabriel** [tomasmcguinness/dotnet-passbook#82]
Hi @tomasmcguinness ,

Is there a way to manually invoke the API methods "GetPass()" and "GetDevicePasses()" from iPhone? Or any steps for it to be invoked?

        [HttpGet]
        [Route("devices/{deviceLibraryIdentifier}/registrations/{passTypeIdentifier}/{passesUpdatedSince?}")]
        public IHttpActionResult GetDevicePasses(string deviceLibraryIdentifier, string passTypeIdentifier, string passesUpdatedSince = null)

        [HttpGet]
        [Route("passes/{passTypeIdentifier}/{serialNumber}")]
        public IHttpActionResult GetPass(string passTypeIdentifier, string serialNumber)

**Comment by tomasmcguinness** [comment]
You could always construct the URL and open it in Safari.

What are you trying to achieve?

**Comment by mcabriel** [comment]
Yes, been doing that during the dev phase.
Now on the Test/QA phase, the API is deployed in test environment and I want to replicate it or rather invoke the methods from iPhone.

Actually, I have invoked the GetPass() API method when we send the PushNotification to the device.

Do you know when exactly the iPhone/Pass wallet App will trigger or invoke the GetDevicePasses() API method?

**Comment by tomasmcguinness** [comment]
So when the pass is initially installed, the RegisterDevicePass() is called.

When a push notification is sent to the device, it will call GetDevicePasses with a value for passesUpdatedSince. 

The server works out the passes that have changed since passesUpdatedSince. It then returns a list of serial numbers.

The device then invokes GetPass for each of the passes that were returned by the called to GetDevicePasses.

Does that help?

**Comment by mcabriel** [comment]
Hi Tomas,

It seems that after I send push notification to a device, it will call GetPass for each of the passes exists in the iPhone. But based on the logs, the GetDevicePasses was never called. Do I missed something?

Also, do you have any idea why it returns 405 status code when removing / unregistering a pass? The pass wallet in iPhone cant reach the UnregisterPass method. All of the routes are the same with HTTPDelete method.

**Comment by tomasmcguinness** [comment]
Maybe if there only one instance of particular pass type identifier, it goes straight to the GetPass().

**Comment by tomasmcguinness** [comment]
I'm going to close this issue as #81 covers the 405 status code issue.
