### ISSUE TITLE
Notification : sslStream timeout

### ISSUE THREAD

**Issue by xavierlaffargue** [tomasmcguinness/dotnet-passbook#84]
Hey,

First thank you for you repo !
I've only 1 issue, when I send the push for updated my pass, It's work. But when it's read the ssl stream, nothing happen for 5 minutes, and I received a timeout

**Comment by tomasmcguinness** [comment]
Hello.

Where are you seeing the sslStream timeout?

**Comment by xav-stargate** [comment]
Class iPhoneMobileNotificationService

 sslStream.Read(response, 0, 6); <===

**Comment by tomasmcguinness** [comment]
That code is trying read a response from APNS, which I don't think you'll get! I think that's a mistake in my code. You can comment that out for the time being.

**Comment by xav-stargate** [comment]
Ok, so there are no possibilities to get a response actually ?

**Comment by tomasmcguinness** [comment]
There is, but it's just a diagnostic response (telling you the push was received etc.). It is returned when the initial request asks for it. I haven't had time to confirm the initial request is correct. Apple's binary protocol is legacy as I need to do a deep search to find the details. The push should work correctly without that line, so to get you moving, you can just comment it out without any ill effect.

If you do find this library useful, please consider support me to help keep it up-to-date - https://www.buymeacoffee.com/fMKJ2NnQ3

**Comment by AshleyMedway** [comment]
@xav-stargate I had this same problem at the weekend. Just remove the read and everything works fine.

**Comment by tomasmcguinness** [comment]
Thanks @AshleyMedway. @xav-stargate when time permits, I'll look into the configuration of the binary request to ensure it doesn't request a response.

**Comment by vinothselvaraj** [comment]
Can u please help on implementing backend service for getting latest version of pass?

**Comment by tomasmcguinness** [comment]
@vinothselvaraj I've created a new issue as adding to this one doesn't seem like a good idea. Please ask your question over at https://github.com/tomasmcguinness/dotnet-passbook/issues/97

**Comment by tomasmcguinness** [comment]
I'm closing this ticket due to it's age.
