### ISSUE TITLE
"Failed to sign manifest" when running on server side

### ISSUE THREAD

**Issue by elchris78** [tomasmcguinness/dotnet-passbook#90]
I'm passing the certificate by reading all bytes from certificate file and set them to .Certificate property of the PassGeneratorRequest object. When I run the process on my machine works like a charm, but when I run it on server side got an exception that says: "Failed to sign manifest". Is there a permission policy specification that has to be set, or what could it be wrong? Thanks in advance.

**Comment by tomasmcguinness** [comment]
How are you running the code on the server side?

**Comment by elchris78** [comment]
It is running on IIS, I´ve got a folder inside the project which contains the .p12 certificate. It's an API service, there is a resource that handles the passbook creation and download. I am not installing the certificate in the MMC. 
Here, I am passing the bytes by reading the certificate data:
![Screenshot_1](https://user-images.githubusercontent.com/20014863/55490283-c361f680-55f0-11e9-889e-4b0431585ea0.png)
Thanks!

**Comment by tomasmcguinness** [comment]
The only thing that comes to mind is the https://github.com/tomasmcguinness/dotnet-passbook#iis-security section, but I don't think that applies to you as you're reading the certificate from disc. 

One thing to try. In the App Pool of your Website, set the Load User Profile setting to true. You should find this under Advanced Settings.

**Comment by elchris78** [comment]
I'v tried all that before. At the first hand, we had my code set to find the certificate from MMC by setting the thumbprint and all the paremeters needed, and everything was working smooth. The original passbook certificate expired days ago and I created a new one, problems came to place since then. My code couldn't find the certificate anymore by searching on the certificate store, that's why I decided to change the aproach, I tried reading it from disc with no luck (Failed to sign manifest). Since it is not working, I've been trying multiple things but nothing works, I'm kind of desperate right now and don't know what else to do in order for this to work like before!

**Comment by tomasmcguinness** [comment]
If you wish, send the certificate to me and I can have a look over the weekend for you.

**Comment by elchris78** [comment]
I am sorry Tomas, I thought you haven´t answered, my bad!
I'm still stock with it =(    
The thing is that, if a run my program in debug mode, I look for the certificate in the certificate store from my machine, and everything works just fine, but when I do it on the server it doesn't, keep throwing "Failed to sign manifest" message.
Which email I can reach you to?  Thank you again!

**Comment by AshleyMedway** [comment]
What code are you using to load the certificate? Have you definitely installed both the private and public keys on the server?

**Comment by elchris78** [comment]
Hey Ashley, this is the code (the one on this git)
(I've tried loading the certificate as byte, and through WCS, and both ways got the same result)

`WebClient client = new WebClient();
 PassGenerator generator = new PassGenerator();
 PassGeneratorRequest passGenerator = new PassGeneratorRequest();
 passGenerator.TeamIdentifier = ConfigurationManager.AppSettings["TeamIdentifier"];
 passGenerator.PassTypeIdentifier = ConfigurationManager.AppSettings["PassTypeIdentifier"];
 passGenerator.OrganizationName = "The Organization";
 passGenerator.Description = request.event_ticket.movie.name;
 passGenerator.SerialNumber = Guid.NewGuid().ToString("N");
 passGenerator.LogoText = string.Empty; /*"The Cinema";*/
 passGenerator.BackgroundColor = "rgb(108,206,255)";
 passGenerator.LabelColor = "rgb(241,250,255)";
 passGenerator.ForegroundColor = "rgb(108,206,255)";                
 //passGenerator.Certificate = await 
GetFileContentAsync(HttpContext.Current.Server.MapPath($"~/Certificate/{ConfigurationManager.AppSettings["PassBookCertificateName"]}"));                
passGenerator.CertThumbprint = ConfigurationManager.AppSettings["PassBookCertificateThumbprint"];
passGenerator.CertLocation = StoreLocation.CurrentUser;
passGenerator.CertificatePassword = ConfigurationManager.AppSettings["PasswordCertificate"];
passGenerator.Images.Add(PassbookImage.Logo,
File.ReadAllBytes(HttpContext.Current.Server.MapPath("~/Content/img/logo.png")));
passGenerator.Images.Add(PassbookImage.LogoRetina,
File.ReadAllBytes(HttpContext.Current.Server.MapPath("~/Content/img/logo.png")));
var background = client.DownloadData(request.event_ticket.movie.image_thumb);
client.Dispose();
passGenerator.Images.Add(PassbookImage.Thumbnail, background.Length > 0 ? background : File.ReadAllBytes(HttpContext.Current.Server.MapPath("~/Content/img/generic-poster.png")));
passGenerator.Images.Add(PassbookImage.ThumbnailRetina, background.Length > 0 ? background : File.ReadAllBytes(HttpContext.Current.Server.MapPath("~/Content/img/generic-poster.png")));
passGenerator.Images.Add(PassbookImage.Background,File.ReadAllBytes(HttpContext.Current.Server.MapPath("~/Content/img/background.png")));
passGenerator.Images.Add(PassbookImage.BackgroundRetina, File.ReadAllBytes(HttpContext.Current.Server.MapPath("~/Content/img/background.png")));
passGenerator.Images.Add(PassbookImage.Icon,
File.ReadAllBytes(HttpContext.Current.Server.MapPath("~/Content/img/logo.png")));
passGenerator.Images.Add(PassbookImage.IconRetina,
File.ReadAllBytes(HttpContext.Current.Server.MapPath("~/Content/img/logo.png")));
passGenerator.AddLocation(request.event_ticket.cinema.latitude, request.event_ticket.cinema.longitude);
passGenerator.AddHeaderField(new StandardField("date",request.event_ticket.movie_projection_date.ToLongDateString(),request.event_ticket.movie_projection_date.ToString("hh:mm tt")));
passGenerator.AddPrimaryField(new StandardField("movie-title","MOVIE",request.event_ticket.movie.name));
passGenerator.AddSecondaryField(new StandardField("cinema-name", "NAME",
request.event_ticket.cinema.name));
if (request.event_ticket.seating != null)
          {
                passGenerator.AddAuxiliaryField(new StandardField("seats", "SEATS",
                request.event_ticket.seating.identify));
           }

passGenerator.AddAuxiliaryField(
new StandardField("auditorium", "AUDITORIUM", request.event_ticket.room));
passGenerator.AddBarcode(BarcodeType.PKBarcodeFormatQR, request.data.booking_id, "UTF-8");
passGenerator.RelevantDate = DateTime.ParseExact(request.event_ticket.movie_projection_date.ToString("yyyy-MM-ddTHH:mm:ss-zzz"), "yyyy-MM-ddTHH:mm:ss-zzz", CultureInfo.InvariantCulture);
passGenerator.WebServiceUrl = "https://api.passdock.com";
passGenerator.Style = PassStyle.EventTicket;
byte[] generatedPass = generator.Generate(passGenerator);
DownloadPKPass(generatedPass);`

**Comment by AshleyMedway** [comment]
For me I had to use certificate location LocalMachine, just make sure you install the certificate to the LocalMachine location on the server and make sure your IIS user has permissions to read the public and private key. I’m away till Monday but could put a demo together of what I did then

**Comment by elchris78** [comment]
I just changed that part having the same result. I am checking all the points you mentioned, I'll let you know the results in short.
![image](https://user-images.githubusercontent.com/20014863/57938209-54351e80-788d-11e9-9d12-8c179de13cb2.png)

**Comment by elchris78** [comment]
I granted IIS user permisions for managing private keys, but don't know where to do this for public keys.
![image](https://user-images.githubusercontent.com/20014863/57939057-10431900-788f-11e9-936c-e0b0e12e408b.png)

![image](https://user-images.githubusercontent.com/20014863/57939004-fc97b280-788e-11e9-976e-a389516dde57.png)

**Comment by elchris78** [comment]
Finally it works!!! =)  
Changed the thumbprint value as it is (with spaces) 
![image](https://user-images.githubusercontent.com/20014863/57939841-cc511380-7890-11e9-8d30-70fdc224a207.png)
Got rid of a space in the begining of the thumbprint string (not visible)
Change the certificate location to LocalMachine, and that was it!
Thank you for your time and comments, I really appreciated it @AshleyMedway and @tomasmcguinness

**Comment by AshleyMedway** [comment]
You need to do it for the app pool too.

IIS APPPOOLS\MyAppPoolName

Or if you run your app pool as a domain user then that same user will need access

**Comment by AshleyMedway** [comment]
@elchris78 awesome! Have fun with your project

**Comment by elchris78** [comment]
Thanks @AshleyMedway ! have a greate day! Cheers from Mexico! =)

**Comment by tomasmcguinness** [comment]
@AshleyMedway Thanks!
