### ISSUE TITLE
Is possible work framework 4.0?

### ISSUE THREAD

**Issue by RubensFex** [tomasmcguinness/dotnet-passbook#92]
Is possible work framework 4.0?

**Comment by RubensFex** [comment]
i want to say, if it´s possible do you compile to framework 4.0?

**Comment by tomasmcguinness** [comment]
Hi. 

No, unfortunately not. It uses ZIP support in the System.IO.Compression library, which isn't available in .Net 4.0. 

.Net 4.5 I believe was the minimum version.

You're welcome to fork the repository and modify it with a different ZIP provider.

Tom
