### ISSUE TITLE
GetPass API as async

### ISSUE THREAD

**Issue by sairaut** [tomasmcguinness/dotnet-passbook#93]
Hi Tom,

In case of bulk push notifications sent to devices, should we make the GetDevicePasses, GetPass APIs as async to handle bulk calls back from devices? Say you have 50K+ customers and you send push notifications to them, then GetPass will be called and server will have load, in this case should we have asyc await mechanism for GetPass? 
Have you came across this scenario?

**Comment by tomasmcguinness** [comment]
No, I haven't designed APIs to work with that number of requests in a short period of time. Async works very well in C# when used to await networking calls. If you're checking a database for example, to ensure a new pass is required or to load the data necessary to generate the pass, than async can be beneficial.
