### ISSUE TITLE
Update process clarification

### ISSUE THREAD

**Issue by tnadolski1** [tomasmcguinness/dotnet-passbook#94]
I'm trying update the pass, but I think the readme is out of date. I don't see the PassRegistrationController in the project. 

From my understanding, we just need to include the webserviceurl (our server), and an authenticationtoken for the request. 

Where does the authenticationtoken come from?

Is there any more information required beyond these two request fields?

Thank you for any help!

**Comment by tomasmcguinness** [comment]
As per Apple's documentation, you're responsible for defining what the authentication token is. It's just included in the pass when it's generated. Typically, you would use the serial number and authentication token to ensure the request is from the owner of the pass and no a 3rd party. 

The Web project I've provided has sadly fallen out of support and it has not been updated in some time.

**Comment by tnadolski1** [comment]
Thanks, Tom! 

And these two fields are all that's required for automatic updates, do you know?
I appreciate the help, thank you so much.

**Comment by tomasmcguinness** [comment]
From the pass, you need the webServiceUrl value and the authenticationToken.

On the service side, you need a mechanism to send the empty notifications and an API that matches Apple's protocol.

I'm updating my reference project right now (long overdue) so you'll be able to use that as a reference in a day or so.

**Comment by tnadolski1** [comment]
Thanks Tom!

**Comment by tomasmcguinness** [comment]
Your welcome.

If you do find the library useful, please consider donating - https://www.buymeacoffee.com/fMKJ2NnQ3

**Comment by tnadolski1** [comment]
Just did. I probably owe you alot more than that haha.
