### ISSUE TITLE
Issue with posting Logs to table

### ISSUE THREAD

**Issue by tnadolski1** [tomasmcguinness/dotnet-passbook#95]
Hi again,

having issues with an iphone posting logging information to a table. Has anyone been able to implement this?

I have an apicontroller setup for a HTTPPOST request to webServiceURL/version/log

I can post directly to it through postman, however, my iphone doesn't send any information on it's own. 

Any advice :)

**Comment by tomasmcguinness** [comment]
Hi. What was the issue?

**Comment by tnadolski1** [comment]
I ended up posting this on Stackoverflow.

This isn't a problem with the library, just a problem my code. So I figured it wasn't appropriate to have an "issue" opened here. But I'm still looking for advice if you have any :)

**Comment by tomasmcguinness** [comment]
First thing to check - are you using HTTPS in your webserviceUrl value?

**Comment by tnadolski1** [comment]
I am,

The weird part is I have the Post request for registering the device, the delete require for unregistering the device, and the Get request for serial numbers operating as intended.

This looks like it's the only REST request not communicating correctly back to the table.

**Comment by tnadolski1** [comment]
[IDCardPass (24).zip](https://github.com/tomasmcguinness/dotnet-passbook/files/3372834/IDCardPass.24.zip)

**Comment by tnadolski1** [comment]
Also, if this helps, my full code and details are at: https://stackoverflow.com/questions/56940701/passbook-not-posting-log-information-to-table

Thank you for all your help!

**Comment by tomasmcguinness** [comment]
Two things of note:

Firstly, you're missing the organizationName from the pass.json file. I believe this a required field. I really need to add some validation into my generator.

Secondly, I can't ping uatweb4.delta.edu. Is your iPhone connected to a different DNS so it can resolve this IP?

I will do some further investigation later today.

**Comment by tnadolski1** [comment]
OrganizationName is a string in my generator request, so that's strange. 

uatweb4 is a private internal for testing purposes. It will not be reachable.

Thank you!

**Comment by tomasmcguinness** [comment]
Okay - what are you expecting it to log?

**Comment by tnadolski1** [comment]
From what I can compare with other's successes, it should be logging when a device completes other REST requests.

At the moment, I'm having issues with updating my pass, but I'm not certain what's causing it. We have individual passes secured behind authentication and I'm assuming that would be the issue. But I wanted to rely on the logs to show me activity. Then I can diagnose the exact problem from there.

**Comment by tomasmcguinness** [comment]
As best I know, the logging endpoint is only called in the event of errors.

When you push the update, does your webservice get invoked?

**Comment by tnadolski1** [comment]
That I don't know.
How can I verify that?

**Comment by tomasmcguinness** [comment]
I recommend you put some logging in your webservice for now, that can determine when it's called. This url will have a value for passesUpdatedSince in the query string.

Are you returning the correct list of serial numbers?

**Comment by tnadolski1** [comment]
Do you have a recommendation for the best way to do that? My apologies for asking so much.

If I call that get request, I get a list of serial numbers that were updates since the date.

**Comment by tomasmcguinness** [comment]
And if you then call the next URL (passing one of the serial numbers), do you return a complete, zipped PKPass file)

Looks like you're using ASP.Net, so adding logging is supported. There are lots of resources out there. 

How are you hosting the API?

**Comment by tnadolski1** [comment]
Calling the GET request to webServiceURL/version/passes/passTypeIdentifier/serialNumber results me no pkpass at this time. I'm assuming this data should be coming from a column from the sql table, no?

I'll start researching :)

The API is hosted from a server on our side.

**Comment by tomasmcguinness** [comment]
So that will be the problem with the updates. This method should return the current version of the pass.

**Comment by tnadolski1** [comment]
Thanks! I'll see what I can figure out.

**Comment by tnadolski1** [comment]
Do you know if theres a way to redirect to a webpage when the pass pulled down to manually update?
I think I have a good solution if so.
