### ISSUE TITLE
Add mutliple pass in Apple Wallet

### ISSUE THREAD

**Issue by MaksimDzhangirov** [tomasmcguinness/dotnet-passbook#96]
My app has a requirement to add multiple passes in apple wallet. Is it possible to sent multiple passes to user using your library?

**Comment by AshleyMedway** [comment]
Yes, take a look at the sample project: https://github.com/tomasmcguinness/dotnet-passbook/tree/master/Passbook.Sample.Web

**Comment by MaksimDzhangirov** [comment]
Thank you for quick response.
Perhaps I didn’t describe my problem well. My web app sells event tickets to users. So user can buy one or more ticket at once. If the user bought more than one ticket, is it possible to add 2 or more passes to that user's Apple Wallet (a group of passes) using your library? If so, what parameters I need to change in sample project config to enable this option?

**Comment by tomasmcguinness** [comment]
You can have as many passes as you like. Each pass must have a unique serial number. 

For example, if you have a pass type identifier of com.maksim.event, you can have a pass with a serial number of 0001 and another with a serial number of 0002. 

The serial numbers are used to keep passes different. If you want to "group" them together, by a particular event (say a concert), you can use the property GroupingIdentifier. 

Does that help?

**Comment by MaksimDzhangirov** [comment]
I know that each pass must have a unique serial number. 
As far as I understand in your sample project you create a pass and send it to user via link (template file https://github.com/tomasmcguinness/dotnet-passbook/blob/master/Passbook.Sample.Web/Views/Pass/EventTicket.cshtml). Pass file is generated in this controller https://github.com/tomasmcguinness/dotnet-passbook/blob/master/Passbook.Sample.Web/Controllers/PassController.cs. So the question is how I need to change this controller's code to sent multiple passes to Apple Wallet via single link. Is it possible or not? As far as I know only one file (pass) can be sended via link.

**Comment by tomasmcguinness** [comment]
Oh, I understand. No, I don't believe it's possible to download two passes from one link. The user experience is to present the pass and have the user add it to their wallet. You can't present two passes at the same time.

**Comment by MaksimDzhangirov** [comment]
Ok. Thank you very much.
